//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvWAProg3.SancionWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", ConfigurationName="SancionWS.SancionWS")]
    public interface SancionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/SancionWS/obtenerPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/SancionWS/obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.SancionWS.obtenerPorIdResponse obtenerPorId(SoftInvWAProg3.SancionWS.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/SancionWS/obtenerPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/SancionWS/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.obtenerPorIdResponse> obtenerPorIdAsync(SoftInvWAProg3.SancionWS.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/SancionWS/listarSancionesRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/SancionWS/listarSancionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.SancionWS.listarSancionesResponse listarSanciones(SoftInvWAProg3.SancionWS.listarSancionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/SancionWS/listarSancionesRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/SancionWS/listarSancionesResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.listarSancionesResponse> listarSancionesAsync(SoftInvWAProg3.SancionWS.listarSancionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/SancionWS/buscarSancionesFlexibleRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/SancionWS/buscarSancionesFlexibleResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.SancionWS.buscarSancionesFlexibleResponse buscarSancionesFlexible(SoftInvWAProg3.SancionWS.buscarSancionesFlexibleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/SancionWS/buscarSancionesFlexibleRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/SancionWS/buscarSancionesFlexibleResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.buscarSancionesFlexibleResponse> buscarSancionesFlexibleAsync(SoftInvWAProg3.SancionWS.buscarSancionesFlexibleRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class sancionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private circulacionDTO circulacionField;
        
        private int diasSancionField;
        
        private bool diasSancionFieldSpecified;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private System.DateTime fechaTerminoField;
        
        private bool fechaTerminoFieldSpecified;
        
        private string observacionField;
        
        private int sancionIdField;
        
        private bool sancionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public circulacionDTO circulacion {
            get {
                return this.circulacionField;
            }
            set {
                this.circulacionField = value;
                this.RaisePropertyChanged("circulacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int diasSancion {
            get {
                return this.diasSancionField;
            }
            set {
                this.diasSancionField = value;
                this.RaisePropertyChanged("diasSancion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diasSancionSpecified {
            get {
                return this.diasSancionFieldSpecified;
            }
            set {
                this.diasSancionFieldSpecified = value;
                this.RaisePropertyChanged("diasSancionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaTermino {
            get {
                return this.fechaTerminoField;
            }
            set {
                this.fechaTerminoField = value;
                this.RaisePropertyChanged("fechaTermino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaTerminoSpecified {
            get {
                return this.fechaTerminoFieldSpecified;
            }
            set {
                this.fechaTerminoFieldSpecified = value;
                this.RaisePropertyChanged("fechaTerminoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string observacion {
            get {
                return this.observacionField;
            }
            set {
                this.observacionField = value;
                this.RaisePropertyChanged("observacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int sancionId {
            get {
                return this.sancionIdField;
            }
            set {
                this.sancionIdField = value;
                this.RaisePropertyChanged("sancionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sancionIdSpecified {
            get {
                return this.sancionIdFieldSpecified;
            }
            set {
                this.sancionIdFieldSpecified = value;
                this.RaisePropertyChanged("sancionIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class circulacionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int circulacionIdField;
        
        private bool circulacionIdFieldSpecified;
        
        private ejemplarDTO ejemplarField;
        
        private estadoPrestamo estadoPrestamoField;
        
        private bool estadoPrestamoFieldSpecified;
        
        private System.DateTime fechaDevolucionField;
        
        private bool fechaDevolucionFieldSpecified;
        
        private System.DateTime fechaPrestamoField;
        
        private bool fechaPrestamoFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private reservaDTO reservaField;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int circulacionId {
            get {
                return this.circulacionIdField;
            }
            set {
                this.circulacionIdField = value;
                this.RaisePropertyChanged("circulacionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool circulacionIdSpecified {
            get {
                return this.circulacionIdFieldSpecified;
            }
            set {
                this.circulacionIdFieldSpecified = value;
                this.RaisePropertyChanged("circulacionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ejemplarDTO ejemplar {
            get {
                return this.ejemplarField;
            }
            set {
                this.ejemplarField = value;
                this.RaisePropertyChanged("ejemplar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoPrestamo estadoPrestamo {
            get {
                return this.estadoPrestamoField;
            }
            set {
                this.estadoPrestamoField = value;
                this.RaisePropertyChanged("estadoPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoPrestamoSpecified {
            get {
                return this.estadoPrestamoFieldSpecified;
            }
            set {
                this.estadoPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("estadoPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaDevolucion {
            get {
                return this.fechaDevolucionField;
            }
            set {
                this.fechaDevolucionField = value;
                this.RaisePropertyChanged("fechaDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDevolucionSpecified {
            get {
                return this.fechaDevolucionFieldSpecified;
            }
            set {
                this.fechaDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("fechaDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaPrestamo {
            get {
                return this.fechaPrestamoField;
            }
            set {
                this.fechaPrestamoField = value;
                this.RaisePropertyChanged("fechaPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPrestamoSpecified {
            get {
                return this.fechaPrestamoFieldSpecified;
            }
            set {
                this.fechaPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("fechaPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public reservaDTO reserva {
            get {
                return this.reservaField;
            }
            set {
                this.reservaField = value;
                this.RaisePropertyChanged("reserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class ejemplarDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bibliotecaDTO bibliotecaField;
        
        private int ejemplarIdField;
        
        private bool ejemplarIdFieldSpecified;
        
        private bool eliminableField;
        
        private bool eliminableFieldSpecified;
        
        private estadoEjemplar estadoField;
        
        private bool estadoFieldSpecified;
        
        private string locacionEnBibliotecaField;
        
        private materialDTO materialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bibliotecaDTO biblioteca {
            get {
                return this.bibliotecaField;
            }
            set {
                this.bibliotecaField = value;
                this.RaisePropertyChanged("biblioteca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ejemplarId {
            get {
                return this.ejemplarIdField;
            }
            set {
                this.ejemplarIdField = value;
                this.RaisePropertyChanged("ejemplarId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejemplarIdSpecified {
            get {
                return this.ejemplarIdFieldSpecified;
            }
            set {
                this.ejemplarIdFieldSpecified = value;
                this.RaisePropertyChanged("ejemplarIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool eliminable {
            get {
                return this.eliminableField;
            }
            set {
                this.eliminableField = value;
                this.RaisePropertyChanged("eliminable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eliminableSpecified {
            get {
                return this.eliminableFieldSpecified;
            }
            set {
                this.eliminableFieldSpecified = value;
                this.RaisePropertyChanged("eliminableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public estadoEjemplar estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string locacionEnBiblioteca {
            get {
                return this.locacionEnBibliotecaField;
            }
            set {
                this.locacionEnBibliotecaField = value;
                this.RaisePropertyChanged("locacionEnBiblioteca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public materialDTO material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class bibliotecaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bibliotecaIdField;
        
        private bool bibliotecaIdFieldSpecified;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int bibliotecaId {
            get {
                return this.bibliotecaIdField;
            }
            set {
                this.bibliotecaIdField = value;
                this.RaisePropertyChanged("bibliotecaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bibliotecaIdSpecified {
            get {
                return this.bibliotecaIdFieldSpecified;
            }
            set {
                this.bibliotecaIdFieldSpecified = value;
                this.RaisePropertyChanged("bibliotecaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class tipoUsuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int numeroMaxDiasField;
        
        private bool numeroMaxDiasFieldSpecified;
        
        private int numeroMaxItemsField;
        
        private bool numeroMaxItemsFieldSpecified;
        
        private int tipoUsuarioIdField;
        
        private bool tipoUsuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroMaxDias {
            get {
                return this.numeroMaxDiasField;
            }
            set {
                this.numeroMaxDiasField = value;
                this.RaisePropertyChanged("numeroMaxDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxDiasSpecified {
            get {
                return this.numeroMaxDiasFieldSpecified;
            }
            set {
                this.numeroMaxDiasFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxDiasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroMaxItems {
            get {
                return this.numeroMaxItemsField;
            }
            set {
                this.numeroMaxItemsField = value;
                this.RaisePropertyChanged("numeroMaxItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxItemsSpecified {
            get {
                return this.numeroMaxItemsFieldSpecified;
            }
            set {
                this.numeroMaxItemsFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipoUsuarioId {
            get {
                return this.tipoUsuarioIdField;
            }
            set {
                this.tipoUsuarioIdField = value;
                this.RaisePropertyChanged("tipoUsuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioIdSpecified {
            get {
                return this.tipoUsuarioIdFieldSpecified;
            }
            set {
                this.tipoUsuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoUniversitarioField;
        
        private string correoElectronicoField;
        
        private estadoUsuario estadoField;
        
        private bool estadoFieldSpecified;
        
        private string nombresField;
        
        private string numeroDocumentoField;
        
        private string passwordField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private tipoUsuarioDTO tipoUsuarioField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoUniversitario {
            get {
                return this.codigoUniversitarioField;
            }
            set {
                this.codigoUniversitarioField = value;
                this.RaisePropertyChanged("codigoUniversitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoUsuario estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public tipoUsuarioDTO tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoUsuario {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        SANCIONADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        PASAPORTE,
        
        /// <remarks/>
        CARNET_DE_EXTRANJERIA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class reservaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoReserva estadoReservaField;
        
        private bool estadoReservaFieldSpecified;
        
        private System.DateTime fechaReservaField;
        
        private bool fechaReservaFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private materialDTO materialField;
        
        private int reservaIdField;
        
        private bool reservaIdFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoReserva estadoReserva {
            get {
                return this.estadoReservaField;
            }
            set {
                this.estadoReservaField = value;
                this.RaisePropertyChanged("estadoReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoReservaSpecified {
            get {
                return this.estadoReservaFieldSpecified;
            }
            set {
                this.estadoReservaFieldSpecified = value;
                this.RaisePropertyChanged("estadoReservaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaReserva {
            get {
                return this.fechaReservaField;
            }
            set {
                this.fechaReservaField = value;
                this.RaisePropertyChanged("fechaReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaReservaSpecified {
            get {
                return this.fechaReservaFieldSpecified;
            }
            set {
                this.fechaReservaFieldSpecified = value;
                this.RaisePropertyChanged("fechaReservaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public materialDTO material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int reservaId {
            get {
                return this.reservaIdField;
            }
            set {
                this.reservaIdField = value;
                this.RaisePropertyChanged("reservaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reservaIdSpecified {
            get {
                return this.reservaIdFieldSpecified;
            }
            set {
                this.reservaIdFieldSpecified = value;
                this.RaisePropertyChanged("reservaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoReserva {
        
        /// <remarks/>
        VIGENTE,
        
        /// <remarks/>
        VENCIDA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class materialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anioPublicacionField;
        
        private bool anioPublicacionFieldSpecified;
        
        private string autorField;
        
        private string idiomaField;
        
        private int materialIdField;
        
        private bool materialIdFieldSpecified;
        
        private int numeroPaginasField;
        
        private bool numeroPaginasFieldSpecified;
        
        private string temaField;
        
        private tipoMaterial tipoMaterialField;
        
        private bool tipoMaterialFieldSpecified;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anioPublicacion {
            get {
                return this.anioPublicacionField;
            }
            set {
                this.anioPublicacionField = value;
                this.RaisePropertyChanged("anioPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioPublicacionSpecified {
            get {
                return this.anioPublicacionFieldSpecified;
            }
            set {
                this.anioPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("anioPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int materialId {
            get {
                return this.materialIdField;
            }
            set {
                this.materialIdField = value;
                this.RaisePropertyChanged("materialId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialIdSpecified {
            get {
                return this.materialIdFieldSpecified;
            }
            set {
                this.materialIdFieldSpecified = value;
                this.RaisePropertyChanged("materialIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPaginas {
            get {
                return this.numeroPaginasField;
            }
            set {
                this.numeroPaginasField = value;
                this.RaisePropertyChanged("numeroPaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroPaginasSpecified {
            get {
                return this.numeroPaginasFieldSpecified;
            }
            set {
                this.numeroPaginasFieldSpecified = value;
                this.RaisePropertyChanged("numeroPaginasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tema {
            get {
                return this.temaField;
            }
            set {
                this.temaField = value;
                this.RaisePropertyChanged("tema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoMaterial tipoMaterial {
            get {
                return this.tipoMaterialField;
            }
            set {
                this.tipoMaterialField = value;
                this.RaisePropertyChanged("tipoMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMaterialSpecified {
            get {
                return this.tipoMaterialFieldSpecified;
            }
            set {
                this.tipoMaterialFieldSpecified = value;
                this.RaisePropertyChanged("tipoMaterialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum tipoMaterial {
        
        /// <remarks/>
        LIBRO,
        
        /// <remarks/>
        ARTICULO,
        
        /// <remarks/>
        TESIS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoEjemplar {
        
        /// <remarks/>
        DISPONIBLE,
        
        /// <remarks/>
        PRESTADO,
        
        /// <remarks/>
        EN_REPARACION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoPrestamo {
        
        /// <remarks/>
        VIGENTE,
        
        /// <remarks/>
        DEVUELTO_A_TIEMPO,
        
        /// <remarks/>
        DEVUELTO_CON_RETRASO,
        
        /// <remarks/>
        DEVUELTO_DANADO_O_PERDIDO,
        
        /// <remarks/>
        DEVUELTO_RETRASO_Y_DANO_PERDIDA,
        
        /// <remarks/>
        NO_DEVUELTO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.SancionWS.sancionDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftInvWAProg3.SancionWS.sancionDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSanciones", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSancionesRequest {
        
        public listarSancionesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSancionesResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSancionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.SancionWS.sancionDTO[] @return;
        
        public listarSancionesResponse() {
        }
        
        public listarSancionesResponse(SoftInvWAProg3.SancionWS.sancionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarSancionesFlexible", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarSancionesFlexibleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sancionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string circulacionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaDesde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaHasta;
        
        public buscarSancionesFlexibleRequest() {
        }
        
        public buscarSancionesFlexibleRequest(string sancionId, string circulacionId, string fechaDesde, string fechaHasta) {
            this.sancionId = sancionId;
            this.circulacionId = circulacionId;
            this.fechaDesde = fechaDesde;
            this.fechaHasta = fechaHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarSancionesFlexibleResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarSancionesFlexibleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.SancionWS.sancionDTO[] @return;
        
        public buscarSancionesFlexibleResponse() {
        }
        
        public buscarSancionesFlexibleResponse(SoftInvWAProg3.SancionWS.sancionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SancionWSChannel : SoftInvWAProg3.SancionWS.SancionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SancionWSClient : System.ServiceModel.ClientBase<SoftInvWAProg3.SancionWS.SancionWS>, SoftInvWAProg3.SancionWS.SancionWS {
        
        public SancionWSClient() {
        }
        
        public SancionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SancionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SancionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SancionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.SancionWS.obtenerPorIdResponse SoftInvWAProg3.SancionWS.SancionWS.obtenerPorId(SoftInvWAProg3.SancionWS.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftInvWAProg3.SancionWS.sancionDTO obtenerPorId(int id) {
            SoftInvWAProg3.SancionWS.obtenerPorIdRequest inValue = new SoftInvWAProg3.SancionWS.obtenerPorIdRequest();
            inValue.id = id;
            SoftInvWAProg3.SancionWS.obtenerPorIdResponse retVal = ((SoftInvWAProg3.SancionWS.SancionWS)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.obtenerPorIdResponse> SoftInvWAProg3.SancionWS.SancionWS.obtenerPorIdAsync(SoftInvWAProg3.SancionWS.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.obtenerPorIdResponse> obtenerPorIdAsync(int id) {
            SoftInvWAProg3.SancionWS.obtenerPorIdRequest inValue = new SoftInvWAProg3.SancionWS.obtenerPorIdRequest();
            inValue.id = id;
            return ((SoftInvWAProg3.SancionWS.SancionWS)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.SancionWS.listarSancionesResponse SoftInvWAProg3.SancionWS.SancionWS.listarSanciones(SoftInvWAProg3.SancionWS.listarSancionesRequest request) {
            return base.Channel.listarSanciones(request);
        }
        
        public SoftInvWAProg3.SancionWS.sancionDTO[] listarSanciones() {
            SoftInvWAProg3.SancionWS.listarSancionesRequest inValue = new SoftInvWAProg3.SancionWS.listarSancionesRequest();
            SoftInvWAProg3.SancionWS.listarSancionesResponse retVal = ((SoftInvWAProg3.SancionWS.SancionWS)(this)).listarSanciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.listarSancionesResponse> SoftInvWAProg3.SancionWS.SancionWS.listarSancionesAsync(SoftInvWAProg3.SancionWS.listarSancionesRequest request) {
            return base.Channel.listarSancionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.listarSancionesResponse> listarSancionesAsync() {
            SoftInvWAProg3.SancionWS.listarSancionesRequest inValue = new SoftInvWAProg3.SancionWS.listarSancionesRequest();
            return ((SoftInvWAProg3.SancionWS.SancionWS)(this)).listarSancionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.SancionWS.buscarSancionesFlexibleResponse SoftInvWAProg3.SancionWS.SancionWS.buscarSancionesFlexible(SoftInvWAProg3.SancionWS.buscarSancionesFlexibleRequest request) {
            return base.Channel.buscarSancionesFlexible(request);
        }
        
        public SoftInvWAProg3.SancionWS.sancionDTO[] buscarSancionesFlexible(string sancionId, string circulacionId, string fechaDesde, string fechaHasta) {
            SoftInvWAProg3.SancionWS.buscarSancionesFlexibleRequest inValue = new SoftInvWAProg3.SancionWS.buscarSancionesFlexibleRequest();
            inValue.sancionId = sancionId;
            inValue.circulacionId = circulacionId;
            inValue.fechaDesde = fechaDesde;
            inValue.fechaHasta = fechaHasta;
            SoftInvWAProg3.SancionWS.buscarSancionesFlexibleResponse retVal = ((SoftInvWAProg3.SancionWS.SancionWS)(this)).buscarSancionesFlexible(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.buscarSancionesFlexibleResponse> SoftInvWAProg3.SancionWS.SancionWS.buscarSancionesFlexibleAsync(SoftInvWAProg3.SancionWS.buscarSancionesFlexibleRequest request) {
            return base.Channel.buscarSancionesFlexibleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.SancionWS.buscarSancionesFlexibleResponse> buscarSancionesFlexibleAsync(string sancionId, string circulacionId, string fechaDesde, string fechaHasta) {
            SoftInvWAProg3.SancionWS.buscarSancionesFlexibleRequest inValue = new SoftInvWAProg3.SancionWS.buscarSancionesFlexibleRequest();
            inValue.sancionId = sancionId;
            inValue.circulacionId = circulacionId;
            inValue.fechaDesde = fechaDesde;
            inValue.fechaHasta = fechaHasta;
            return ((SoftInvWAProg3.SancionWS.SancionWS)(this)).buscarSancionesFlexibleAsync(inValue);
        }
    }
}
