//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvWAProg3.EjemplarWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class materialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anioPublicacionField;
        
        private bool anioPublicacionFieldSpecified;
        
        private string autorField;
        
        private string idiomaField;
        
        private int materialIdField;
        
        private bool materialIdFieldSpecified;
        
        private int numeroPaginasField;
        
        private bool numeroPaginasFieldSpecified;
        
        private string temaField;
        
        private tipoMaterial tipoMaterialField;
        
        private bool tipoMaterialFieldSpecified;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anioPublicacion {
            get {
                return this.anioPublicacionField;
            }
            set {
                this.anioPublicacionField = value;
                this.RaisePropertyChanged("anioPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioPublicacionSpecified {
            get {
                return this.anioPublicacionFieldSpecified;
            }
            set {
                this.anioPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("anioPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int materialId {
            get {
                return this.materialIdField;
            }
            set {
                this.materialIdField = value;
                this.RaisePropertyChanged("materialId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialIdSpecified {
            get {
                return this.materialIdFieldSpecified;
            }
            set {
                this.materialIdFieldSpecified = value;
                this.RaisePropertyChanged("materialIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPaginas {
            get {
                return this.numeroPaginasField;
            }
            set {
                this.numeroPaginasField = value;
                this.RaisePropertyChanged("numeroPaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroPaginasSpecified {
            get {
                return this.numeroPaginasFieldSpecified;
            }
            set {
                this.numeroPaginasFieldSpecified = value;
                this.RaisePropertyChanged("numeroPaginasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tema {
            get {
                return this.temaField;
            }
            set {
                this.temaField = value;
                this.RaisePropertyChanged("tema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoMaterial tipoMaterial {
            get {
                return this.tipoMaterialField;
            }
            set {
                this.tipoMaterialField = value;
                this.RaisePropertyChanged("tipoMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMaterialSpecified {
            get {
                return this.tipoMaterialFieldSpecified;
            }
            set {
                this.tipoMaterialFieldSpecified = value;
                this.RaisePropertyChanged("tipoMaterialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum tipoMaterial {
        
        /// <remarks/>
        LIBRO,
        
        /// <remarks/>
        ARTICULO,
        
        /// <remarks/>
        TESIS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class bibliotecaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bibliotecaIdField;
        
        private bool bibliotecaIdFieldSpecified;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int bibliotecaId {
            get {
                return this.bibliotecaIdField;
            }
            set {
                this.bibliotecaIdField = value;
                this.RaisePropertyChanged("bibliotecaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bibliotecaIdSpecified {
            get {
                return this.bibliotecaIdFieldSpecified;
            }
            set {
                this.bibliotecaIdFieldSpecified = value;
                this.RaisePropertyChanged("bibliotecaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class ejemplarDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bibliotecaDTO bibliotecaField;
        
        private int ejemplarIdField;
        
        private bool ejemplarIdFieldSpecified;
        
        private bool eliminableField;
        
        private bool eliminableFieldSpecified;
        
        private estadoEjemplar estadoField;
        
        private bool estadoFieldSpecified;
        
        private string locacionEnBibliotecaField;
        
        private materialDTO materialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bibliotecaDTO biblioteca {
            get {
                return this.bibliotecaField;
            }
            set {
                this.bibliotecaField = value;
                this.RaisePropertyChanged("biblioteca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ejemplarId {
            get {
                return this.ejemplarIdField;
            }
            set {
                this.ejemplarIdField = value;
                this.RaisePropertyChanged("ejemplarId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejemplarIdSpecified {
            get {
                return this.ejemplarIdFieldSpecified;
            }
            set {
                this.ejemplarIdFieldSpecified = value;
                this.RaisePropertyChanged("ejemplarIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool eliminable {
            get {
                return this.eliminableField;
            }
            set {
                this.eliminableField = value;
                this.RaisePropertyChanged("eliminable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eliminableSpecified {
            get {
                return this.eliminableFieldSpecified;
            }
            set {
                this.eliminableFieldSpecified = value;
                this.RaisePropertyChanged("eliminableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public estadoEjemplar estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string locacionEnBiblioteca {
            get {
                return this.locacionEnBibliotecaField;
            }
            set {
                this.locacionEnBibliotecaField = value;
                this.RaisePropertyChanged("locacionEnBiblioteca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public materialDTO material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoEjemplar {
        
        /// <remarks/>
        DISPONIBLE,
        
        /// <remarks/>
        PRESTADO,
        
        /// <remarks/>
        EN_REPARACION,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", ConfigurationName="EjemplarWS.EjemplarWS")]
    public interface EjemplarWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplaresMaterialPorBibliotecaRe" +
            "quest", ReplyAction="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplaresMaterialPorBibliotecaRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.EjemplarWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplaresMaterialPorBiblioteca/F" +
            "ault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaResponse obtenerEjemplaresMaterialPorBiblioteca(SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplaresMaterialPorBibliotecaRe" +
            "quest", ReplyAction="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplaresMaterialPorBibliotecaRe" +
            "sponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaResponse> obtenerEjemplaresMaterialPorBibliotecaAsync(SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/insertarEjemplarRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/EjemplarWS/insertarEjemplarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.EjemplarWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/insertarEjemplar/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.EjemplarWS.insertarEjemplarResponse insertarEjemplar(SoftInvWAProg3.EjemplarWS.insertarEjemplarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/insertarEjemplarRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/EjemplarWS/insertarEjemplarResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.insertarEjemplarResponse> insertarEjemplarAsync(SoftInvWAProg3.EjemplarWS.insertarEjemplarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplarPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplarPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.EjemplarWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplarPorId/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdResponse obtenerEjemplarPorId(SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplarPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/EjemplarWS/obtenerEjemplarPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdResponse> obtenerEjemplarPorIdAsync(SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/listarTodosEjemplaresRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/EjemplarWS/listarTodosEjemplaresResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.EjemplarWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/listarTodosEjemplares/Fault/SQLException" +
            "", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresResponse listarTodosEjemplares(SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/EjemplarWS/listarTodosEjemplaresRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/EjemplarWS/listarTodosEjemplaresResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresResponse> listarTodosEjemplaresAsync(SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEjemplaresMaterialPorBiblioteca", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEjemplaresMaterialPorBibliotecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int materialId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int bibliotecaId;
        
        public obtenerEjemplaresMaterialPorBibliotecaRequest() {
        }
        
        public obtenerEjemplaresMaterialPorBibliotecaRequest(int materialId, int bibliotecaId) {
            this.materialId = materialId;
            this.bibliotecaId = bibliotecaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEjemplaresMaterialPorBibliotecaResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEjemplaresMaterialPorBibliotecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.EjemplarWS.ejemplarDTO[] @return;
        
        public obtenerEjemplaresMaterialPorBibliotecaResponse() {
        }
        
        public obtenerEjemplaresMaterialPorBibliotecaResponse(SoftInvWAProg3.EjemplarWS.ejemplarDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEjemplar", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEjemplarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bibliotecaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string titulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string anioStr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idioma;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string locacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public insertarEjemplarRequest() {
        }
        
        public insertarEjemplarRequest(string bibliotecaId, string titulo, string autor, string tipo, string anioStr, string idioma, string tema, string locacion, string estado) {
            this.bibliotecaId = bibliotecaId;
            this.titulo = titulo;
            this.autor = autor;
            this.tipo = tipo;
            this.anioStr = anioStr;
            this.idioma = idioma;
            this.tema = tema;
            this.locacion = locacion;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEjemplarResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEjemplarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEjemplarResponse() {
        }
        
        public insertarEjemplarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEjemplarPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEjemplarPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idEjemplar;
        
        public obtenerEjemplarPorIdRequest() {
        }
        
        public obtenerEjemplarPorIdRequest(int idEjemplar) {
            this.idEjemplar = idEjemplar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEjemplarPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEjemplarPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.EjemplarWS.ejemplarDTO @return;
        
        public obtenerEjemplarPorIdResponse() {
        }
        
        public obtenerEjemplarPorIdResponse(SoftInvWAProg3.EjemplarWS.ejemplarDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEjemplares", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosEjemplaresRequest {
        
        public listarTodosEjemplaresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEjemplaresResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosEjemplaresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.EjemplarWS.ejemplarDTO[] @return;
        
        public listarTodosEjemplaresResponse() {
        }
        
        public listarTodosEjemplaresResponse(SoftInvWAProg3.EjemplarWS.ejemplarDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EjemplarWSChannel : SoftInvWAProg3.EjemplarWS.EjemplarWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EjemplarWSClient : System.ServiceModel.ClientBase<SoftInvWAProg3.EjemplarWS.EjemplarWS>, SoftInvWAProg3.EjemplarWS.EjemplarWS {
        
        public EjemplarWSClient() {
        }
        
        public EjemplarWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EjemplarWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemplarWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EjemplarWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaResponse SoftInvWAProg3.EjemplarWS.EjemplarWS.obtenerEjemplaresMaterialPorBiblioteca(SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaRequest request) {
            return base.Channel.obtenerEjemplaresMaterialPorBiblioteca(request);
        }
        
        public SoftInvWAProg3.EjemplarWS.ejemplarDTO[] obtenerEjemplaresMaterialPorBiblioteca(int materialId, int bibliotecaId) {
            SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaRequest inValue = new SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaRequest();
            inValue.materialId = materialId;
            inValue.bibliotecaId = bibliotecaId;
            SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaResponse retVal = ((SoftInvWAProg3.EjemplarWS.EjemplarWS)(this)).obtenerEjemplaresMaterialPorBiblioteca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaResponse> SoftInvWAProg3.EjemplarWS.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaAsync(SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaRequest request) {
            return base.Channel.obtenerEjemplaresMaterialPorBibliotecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaResponse> obtenerEjemplaresMaterialPorBibliotecaAsync(int materialId, int bibliotecaId) {
            SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaRequest inValue = new SoftInvWAProg3.EjemplarWS.obtenerEjemplaresMaterialPorBibliotecaRequest();
            inValue.materialId = materialId;
            inValue.bibliotecaId = bibliotecaId;
            return ((SoftInvWAProg3.EjemplarWS.EjemplarWS)(this)).obtenerEjemplaresMaterialPorBibliotecaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.EjemplarWS.insertarEjemplarResponse SoftInvWAProg3.EjemplarWS.EjemplarWS.insertarEjemplar(SoftInvWAProg3.EjemplarWS.insertarEjemplarRequest request) {
            return base.Channel.insertarEjemplar(request);
        }
        
        public int insertarEjemplar(string bibliotecaId, string titulo, string autor, string tipo, string anioStr, string idioma, string tema, string locacion, string estado) {
            SoftInvWAProg3.EjemplarWS.insertarEjemplarRequest inValue = new SoftInvWAProg3.EjemplarWS.insertarEjemplarRequest();
            inValue.bibliotecaId = bibliotecaId;
            inValue.titulo = titulo;
            inValue.autor = autor;
            inValue.tipo = tipo;
            inValue.anioStr = anioStr;
            inValue.idioma = idioma;
            inValue.tema = tema;
            inValue.locacion = locacion;
            inValue.estado = estado;
            SoftInvWAProg3.EjemplarWS.insertarEjemplarResponse retVal = ((SoftInvWAProg3.EjemplarWS.EjemplarWS)(this)).insertarEjemplar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.insertarEjemplarResponse> SoftInvWAProg3.EjemplarWS.EjemplarWS.insertarEjemplarAsync(SoftInvWAProg3.EjemplarWS.insertarEjemplarRequest request) {
            return base.Channel.insertarEjemplarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.insertarEjemplarResponse> insertarEjemplarAsync(string bibliotecaId, string titulo, string autor, string tipo, string anioStr, string idioma, string tema, string locacion, string estado) {
            SoftInvWAProg3.EjemplarWS.insertarEjemplarRequest inValue = new SoftInvWAProg3.EjemplarWS.insertarEjemplarRequest();
            inValue.bibliotecaId = bibliotecaId;
            inValue.titulo = titulo;
            inValue.autor = autor;
            inValue.tipo = tipo;
            inValue.anioStr = anioStr;
            inValue.idioma = idioma;
            inValue.tema = tema;
            inValue.locacion = locacion;
            inValue.estado = estado;
            return ((SoftInvWAProg3.EjemplarWS.EjemplarWS)(this)).insertarEjemplarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdResponse SoftInvWAProg3.EjemplarWS.EjemplarWS.obtenerEjemplarPorId(SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdRequest request) {
            return base.Channel.obtenerEjemplarPorId(request);
        }
        
        public SoftInvWAProg3.EjemplarWS.ejemplarDTO obtenerEjemplarPorId(int idEjemplar) {
            SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdRequest inValue = new SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdRequest();
            inValue.idEjemplar = idEjemplar;
            SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdResponse retVal = ((SoftInvWAProg3.EjemplarWS.EjemplarWS)(this)).obtenerEjemplarPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdResponse> SoftInvWAProg3.EjemplarWS.EjemplarWS.obtenerEjemplarPorIdAsync(SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdRequest request) {
            return base.Channel.obtenerEjemplarPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdResponse> obtenerEjemplarPorIdAsync(int idEjemplar) {
            SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdRequest inValue = new SoftInvWAProg3.EjemplarWS.obtenerEjemplarPorIdRequest();
            inValue.idEjemplar = idEjemplar;
            return ((SoftInvWAProg3.EjemplarWS.EjemplarWS)(this)).obtenerEjemplarPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresResponse SoftInvWAProg3.EjemplarWS.EjemplarWS.listarTodosEjemplares(SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresRequest request) {
            return base.Channel.listarTodosEjemplares(request);
        }
        
        public SoftInvWAProg3.EjemplarWS.ejemplarDTO[] listarTodosEjemplares() {
            SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresRequest inValue = new SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresRequest();
            SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresResponse retVal = ((SoftInvWAProg3.EjemplarWS.EjemplarWS)(this)).listarTodosEjemplares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresResponse> SoftInvWAProg3.EjemplarWS.EjemplarWS.listarTodosEjemplaresAsync(SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresRequest request) {
            return base.Channel.listarTodosEjemplaresAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresResponse> listarTodosEjemplaresAsync() {
            SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresRequest inValue = new SoftInvWAProg3.EjemplarWS.listarTodosEjemplaresRequest();
            return ((SoftInvWAProg3.EjemplarWS.EjemplarWS)(this)).listarTodosEjemplaresAsync(inValue);
        }
    }
}
