//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvWAProg3.DiaAtencionWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class localTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class bibliotecaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bibliotecaIdField;
        
        private bool bibliotecaIdFieldSpecified;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int bibliotecaId {
            get {
                return this.bibliotecaIdField;
            }
            set {
                this.bibliotecaIdField = value;
                this.RaisePropertyChanged("bibliotecaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bibliotecaIdSpecified {
            get {
                return this.bibliotecaIdFieldSpecified;
            }
            set {
                this.bibliotecaIdFieldSpecified = value;
                this.RaisePropertyChanged("bibliotecaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class diaAtencionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bibliotecaDTO bibliotecaField;
        
        private int diaAtencionIdField;
        
        private bool diaAtencionIdFieldSpecified;
        
        private localTime horaFinAtencionField;
        
        private localTime horaInicioAtencionField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bibliotecaDTO biblioteca {
            get {
                return this.bibliotecaField;
            }
            set {
                this.bibliotecaField = value;
                this.RaisePropertyChanged("biblioteca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int diaAtencionId {
            get {
                return this.diaAtencionIdField;
            }
            set {
                this.diaAtencionIdField = value;
                this.RaisePropertyChanged("diaAtencionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaAtencionIdSpecified {
            get {
                return this.diaAtencionIdFieldSpecified;
            }
            set {
                this.diaAtencionIdFieldSpecified = value;
                this.RaisePropertyChanged("diaAtencionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public localTime horaFinAtencion {
            get {
                return this.horaFinAtencionField;
            }
            set {
                this.horaFinAtencionField = value;
                this.RaisePropertyChanged("horaFinAtencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public localTime horaInicioAtencion {
            get {
                return this.horaInicioAtencionField;
            }
            set {
                this.horaInicioAtencionField = value;
                this.RaisePropertyChanged("horaInicioAtencion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", ConfigurationName="DiaAtencionWS.DiaAtencionWS")]
    public interface DiaAtencionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarDiasAtencionPorBibliotecaReques" +
            "t", ReplyAction="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarDiasAtencionPorBibliotecaRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.DiaAtencionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarDiasAtencionPorBiblioteca/Fault" +
            "/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaResponse listarDiasAtencionPorBiblioteca(SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarDiasAtencionPorBibliotecaReques" +
            "t", ReplyAction="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarDiasAtencionPorBibliotecaRespon" +
            "se")]
        System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaResponse> listarDiasAtencionPorBibliotecaAsync(SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarTodosDiasAtencionRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarTodosDiasAtencionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.DiaAtencionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarTodosDiasAtencion/Fault/SQLExce" +
            "ption", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionResponse listarTodosDiasAtencion(SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarTodosDiasAtencionRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/listarTodosDiasAtencionResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionResponse> listarTodosDiasAtencionAsync(SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/obtenerDiaAtencionPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/obtenerDiaAtencionPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.DiaAtencionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/obtenerDiaAtencionPorId/Fault/SQLExce" +
            "ption", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdResponse obtenerDiaAtencionPorId(SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/obtenerDiaAtencionPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/DiaAtencionWS/obtenerDiaAtencionPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdResponse> obtenerDiaAtencionPorIdAsync(SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDiasAtencionPorBiblioteca", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDiasAtencionPorBibliotecaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idBiblioteca;
        
        public listarDiasAtencionPorBibliotecaRequest() {
        }
        
        public listarDiasAtencionPorBibliotecaRequest(int idBiblioteca) {
            this.idBiblioteca = idBiblioteca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDiasAtencionPorBibliotecaResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDiasAtencionPorBibliotecaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO[] @return;
        
        public listarDiasAtencionPorBibliotecaResponse() {
        }
        
        public listarDiasAtencionPorBibliotecaResponse(SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDiasAtencion", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDiasAtencionRequest {
        
        public listarTodosDiasAtencionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDiasAtencionResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDiasAtencionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO[] @return;
        
        public listarTodosDiasAtencionResponse() {
        }
        
        public listarTodosDiasAtencionResponse(SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDiaAtencionPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDiaAtencionPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDiaAtencion;
        
        public obtenerDiaAtencionPorIdRequest() {
        }
        
        public obtenerDiaAtencionPorIdRequest(int idDiaAtencion) {
            this.idDiaAtencion = idDiaAtencion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDiaAtencionPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerDiaAtencionPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO @return;
        
        public obtenerDiaAtencionPorIdResponse() {
        }
        
        public obtenerDiaAtencionPorIdResponse(SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DiaAtencionWSChannel : SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiaAtencionWSClient : System.ServiceModel.ClientBase<SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS>, SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS {
        
        public DiaAtencionWSClient() {
        }
        
        public DiaAtencionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiaAtencionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiaAtencionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiaAtencionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaResponse SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS.listarDiasAtencionPorBiblioteca(SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaRequest request) {
            return base.Channel.listarDiasAtencionPorBiblioteca(request);
        }
        
        public SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO[] listarDiasAtencionPorBiblioteca(int idBiblioteca) {
            SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaRequest inValue = new SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaRequest();
            inValue.idBiblioteca = idBiblioteca;
            SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaResponse retVal = ((SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS)(this)).listarDiasAtencionPorBiblioteca(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaResponse> SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS.listarDiasAtencionPorBibliotecaAsync(SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaRequest request) {
            return base.Channel.listarDiasAtencionPorBibliotecaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaResponse> listarDiasAtencionPorBibliotecaAsync(int idBiblioteca) {
            SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaRequest inValue = new SoftInvWAProg3.DiaAtencionWS.listarDiasAtencionPorBibliotecaRequest();
            inValue.idBiblioteca = idBiblioteca;
            return ((SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS)(this)).listarDiasAtencionPorBibliotecaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionResponse SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS.listarTodosDiasAtencion(SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionRequest request) {
            return base.Channel.listarTodosDiasAtencion(request);
        }
        
        public SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO[] listarTodosDiasAtencion() {
            SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionRequest inValue = new SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionRequest();
            SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionResponse retVal = ((SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS)(this)).listarTodosDiasAtencion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionResponse> SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS.listarTodosDiasAtencionAsync(SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionRequest request) {
            return base.Channel.listarTodosDiasAtencionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionResponse> listarTodosDiasAtencionAsync() {
            SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionRequest inValue = new SoftInvWAProg3.DiaAtencionWS.listarTodosDiasAtencionRequest();
            return ((SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS)(this)).listarTodosDiasAtencionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdResponse SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS.obtenerDiaAtencionPorId(SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdRequest request) {
            return base.Channel.obtenerDiaAtencionPorId(request);
        }
        
        public SoftInvWAProg3.DiaAtencionWS.diaAtencionDTO obtenerDiaAtencionPorId(int idDiaAtencion) {
            SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdRequest inValue = new SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdRequest();
            inValue.idDiaAtencion = idDiaAtencion;
            SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdResponse retVal = ((SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS)(this)).obtenerDiaAtencionPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdResponse> SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS.obtenerDiaAtencionPorIdAsync(SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdRequest request) {
            return base.Channel.obtenerDiaAtencionPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdResponse> obtenerDiaAtencionPorIdAsync(int idDiaAtencion) {
            SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdRequest inValue = new SoftInvWAProg3.DiaAtencionWS.obtenerDiaAtencionPorIdRequest();
            inValue.idDiaAtencion = idDiaAtencion;
            return ((SoftInvWAProg3.DiaAtencionWS.DiaAtencionWS)(this)).obtenerDiaAtencionPorIdAsync(inValue);
        }
    }
}
