//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvWAProg3.ReservaWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", ConfigurationName="ReservaWS.ReservaWS")]
    public interface ReservaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/calcularFechaVencimientoReservaRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/calcularFechaVencimientoReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/calcularFechaVencimientoReserva/Fault/SQL" +
            "Exception", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaResponse calcularFechaVencimientoReserva(SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/calcularFechaVencimientoReservaRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/calcularFechaVencimientoReservaResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaResponse> calcularFechaVencimientoReservaAsync(SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/listarReservasVigentesPorUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/listarReservasVigentesPorUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/listarReservasVigentesPorUsuario/Fault/SQ" +
            "LException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioResponse listarReservasVigentesPorUsuario(SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/listarReservasVigentesPorUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/listarReservasVigentesPorUsuarioResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioResponse> listarReservasVigentesPorUsuarioAsync(SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/insertarReservaRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/insertarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/insertarReserva/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.insertarReservaResponse insertarReserva(SoftInvWAProg3.ReservaWS.insertarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/insertarReservaRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/insertarReservaResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.insertarReservaResponse> insertarReservaAsync(SoftInvWAProg3.ReservaWS.insertarReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/modificarReservaRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/modificarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/modificarReserva/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.modificarReservaResponse modificarReserva(SoftInvWAProg3.ReservaWS.modificarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/modificarReservaRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/modificarReservaResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.modificarReservaResponse> modificarReservaAsync(SoftInvWAProg3.ReservaWS.modificarReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/eliminarReservaRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/eliminarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/eliminarReserva/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.eliminarReservaResponse eliminarReserva(SoftInvWAProg3.ReservaWS.eliminarReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/eliminarReservaRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/eliminarReservaResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.eliminarReservaResponse> eliminarReservaAsync(SoftInvWAProg3.ReservaWS.eliminarReservaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/listarTodasReservasRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/listarTodasReservasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/listarTodasReservas/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.listarTodasReservasResponse listarTodasReservas(SoftInvWAProg3.ReservaWS.listarTodasReservasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/listarTodasReservasRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/listarTodasReservasResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.listarTodasReservasResponse> listarTodasReservasAsync(SoftInvWAProg3.ReservaWS.listarTodasReservasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerTipoDeMaterialPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerTipoDeMaterialPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.Exception), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerTipoDeMaterialPorId/Fault/Exceptio" +
            "n", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdResponse obtenerTipoDeMaterialPorId(SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerTipoDeMaterialPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerTipoDeMaterialPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdResponse> obtenerTipoDeMaterialPorIdAsync(SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/buscarReservasAvanzadoRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/buscarReservasAvanzadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.Exception), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/buscarReservasAvanzado/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoResponse buscarReservasAvanzado(SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/buscarReservasAvanzadoRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/buscarReservasAvanzadoResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoResponse> buscarReservasAvanzadoAsync(SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerReservaPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerReservaPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.ReservaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerReservaPorId/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.ReservaWS.obtenerReservaPorIdResponse obtenerReservaPorId(SoftInvWAProg3.ReservaWS.obtenerReservaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerReservaPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/ReservaWS/obtenerReservaPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.obtenerReservaPorIdResponse> obtenerReservaPorIdAsync(SoftInvWAProg3.ReservaWS.obtenerReservaPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularFechaVencimientoReserva", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class calcularFechaVencimientoReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaReserva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int bibliotecaId;
        
        public calcularFechaVencimientoReservaRequest() {
        }
        
        public calcularFechaVencimientoReservaRequest(System.DateTime fechaReserva, int bibliotecaId) {
            this.fechaReserva = fechaReserva;
            this.bibliotecaId = bibliotecaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="calcularFechaVencimientoReservaResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class calcularFechaVencimientoReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime @return;
        
        public calcularFechaVencimientoReservaResponse() {
        }
        
        public calcularFechaVencimientoReservaResponse(System.DateTime @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class reservaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoReserva estadoReservaField;
        
        private bool estadoReservaFieldSpecified;
        
        private System.DateTime fechaReservaField;
        
        private bool fechaReservaFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private materialDTO materialField;
        
        private int reservaIdField;
        
        private bool reservaIdFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoReserva estadoReserva {
            get {
                return this.estadoReservaField;
            }
            set {
                this.estadoReservaField = value;
                this.RaisePropertyChanged("estadoReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoReservaSpecified {
            get {
                return this.estadoReservaFieldSpecified;
            }
            set {
                this.estadoReservaFieldSpecified = value;
                this.RaisePropertyChanged("estadoReservaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaReserva {
            get {
                return this.fechaReservaField;
            }
            set {
                this.fechaReservaField = value;
                this.RaisePropertyChanged("fechaReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaReservaSpecified {
            get {
                return this.fechaReservaFieldSpecified;
            }
            set {
                this.fechaReservaFieldSpecified = value;
                this.RaisePropertyChanged("fechaReservaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public materialDTO material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int reservaId {
            get {
                return this.reservaIdField;
            }
            set {
                this.reservaIdField = value;
                this.RaisePropertyChanged("reservaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reservaIdSpecified {
            get {
                return this.reservaIdFieldSpecified;
            }
            set {
                this.reservaIdFieldSpecified = value;
                this.RaisePropertyChanged("reservaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoReserva {
        
        /// <remarks/>
        VIGENTE,
        
        /// <remarks/>
        VENCIDA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class materialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anioPublicacionField;
        
        private bool anioPublicacionFieldSpecified;
        
        private string autorField;
        
        private string idiomaField;
        
        private int materialIdField;
        
        private bool materialIdFieldSpecified;
        
        private int numeroPaginasField;
        
        private bool numeroPaginasFieldSpecified;
        
        private string temaField;
        
        private tipoMaterial tipoMaterialField;
        
        private bool tipoMaterialFieldSpecified;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anioPublicacion {
            get {
                return this.anioPublicacionField;
            }
            set {
                this.anioPublicacionField = value;
                this.RaisePropertyChanged("anioPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioPublicacionSpecified {
            get {
                return this.anioPublicacionFieldSpecified;
            }
            set {
                this.anioPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("anioPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int materialId {
            get {
                return this.materialIdField;
            }
            set {
                this.materialIdField = value;
                this.RaisePropertyChanged("materialId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialIdSpecified {
            get {
                return this.materialIdFieldSpecified;
            }
            set {
                this.materialIdFieldSpecified = value;
                this.RaisePropertyChanged("materialIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPaginas {
            get {
                return this.numeroPaginasField;
            }
            set {
                this.numeroPaginasField = value;
                this.RaisePropertyChanged("numeroPaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroPaginasSpecified {
            get {
                return this.numeroPaginasFieldSpecified;
            }
            set {
                this.numeroPaginasFieldSpecified = value;
                this.RaisePropertyChanged("numeroPaginasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tema {
            get {
                return this.temaField;
            }
            set {
                this.temaField = value;
                this.RaisePropertyChanged("tema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoMaterial tipoMaterial {
            get {
                return this.tipoMaterialField;
            }
            set {
                this.tipoMaterialField = value;
                this.RaisePropertyChanged("tipoMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMaterialSpecified {
            get {
                return this.tipoMaterialFieldSpecified;
            }
            set {
                this.tipoMaterialFieldSpecified = value;
                this.RaisePropertyChanged("tipoMaterialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum tipoMaterial {
        
        /// <remarks/>
        LIBRO,
        
        /// <remarks/>
        ARTICULO,
        
        /// <remarks/>
        TESIS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoUniversitarioField;
        
        private string correoElectronicoField;
        
        private estadoUsuario estadoField;
        
        private bool estadoFieldSpecified;
        
        private string nombresField;
        
        private string numeroDocumentoField;
        
        private string passwordField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private tipoUsuarioDTO tipoUsuarioField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoUniversitario {
            get {
                return this.codigoUniversitarioField;
            }
            set {
                this.codigoUniversitarioField = value;
                this.RaisePropertyChanged("codigoUniversitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoUsuario estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public tipoUsuarioDTO tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoUsuario {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        SANCIONADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        PASAPORTE,
        
        /// <remarks/>
        CARNET_DE_EXTRANJERIA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class tipoUsuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int numeroMaxDiasField;
        
        private bool numeroMaxDiasFieldSpecified;
        
        private int numeroMaxItemsField;
        
        private bool numeroMaxItemsFieldSpecified;
        
        private int tipoUsuarioIdField;
        
        private bool tipoUsuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroMaxDias {
            get {
                return this.numeroMaxDiasField;
            }
            set {
                this.numeroMaxDiasField = value;
                this.RaisePropertyChanged("numeroMaxDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxDiasSpecified {
            get {
                return this.numeroMaxDiasFieldSpecified;
            }
            set {
                this.numeroMaxDiasFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxDiasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroMaxItems {
            get {
                return this.numeroMaxItemsField;
            }
            set {
                this.numeroMaxItemsField = value;
                this.RaisePropertyChanged("numeroMaxItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxItemsSpecified {
            get {
                return this.numeroMaxItemsFieldSpecified;
            }
            set {
                this.numeroMaxItemsFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipoUsuarioId {
            get {
                return this.tipoUsuarioIdField;
            }
            set {
                this.tipoUsuarioIdField = value;
                this.RaisePropertyChanged("tipoUsuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioIdSpecified {
            get {
                return this.tipoUsuarioIdFieldSpecified;
            }
            set {
                this.tipoUsuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarReservasVigentesPorUsuario", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarReservasVigentesPorUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usuarioId;
        
        public listarReservasVigentesPorUsuarioRequest() {
        }
        
        public listarReservasVigentesPorUsuarioRequest(int usuarioId) {
            this.usuarioId = usuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarReservasVigentesPorUsuarioResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarReservasVigentesPorUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.ReservaWS.reservaDTO[] @return;
        
        public listarReservasVigentesPorUsuarioResponse() {
        }
        
        public listarReservasVigentesPorUsuarioResponse(SoftInvWAProg3.ReservaWS.reservaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarReserva", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.ReservaWS.reservaDTO reserva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int bibliotecaId;
        
        public insertarReservaRequest() {
        }
        
        public insertarReservaRequest(SoftInvWAProg3.ReservaWS.reservaDTO reserva, int bibliotecaId) {
            this.reserva = reserva;
            this.bibliotecaId = bibliotecaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarReservaResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarReservaResponse() {
        }
        
        public insertarReservaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarReserva", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.ReservaWS.reservaDTO reserva;
        
        public modificarReservaRequest() {
        }
        
        public modificarReservaRequest(SoftInvWAProg3.ReservaWS.reservaDTO reserva) {
            this.reserva = reserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarReservaResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarReservaResponse() {
        }
        
        public modificarReservaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarReserva", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        public eliminarReservaRequest() {
        }
        
        public eliminarReservaRequest(int idReserva) {
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarReservaResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarReservaResponse() {
        }
        
        public eliminarReservaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasReservas", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasReservasRequest {
        
        public listarTodasReservasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasReservasResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasReservasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.ReservaWS.reservaDTO[] @return;
        
        public listarTodasReservasResponse() {
        }
        
        public listarTodasReservasResponse(SoftInvWAProg3.ReservaWS.reservaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTipoDeMaterialPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerTipoDeMaterialPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idMaterial;
        
        public obtenerTipoDeMaterialPorIdRequest() {
        }
        
        public obtenerTipoDeMaterialPorIdRequest(int idMaterial) {
            this.idMaterial = idMaterial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTipoDeMaterialPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerTipoDeMaterialPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public obtenerTipoDeMaterialPorIdResponse() {
        }
        
        public obtenerTipoDeMaterialPorIdResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarReservasAvanzado", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarReservasAvanzadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string reservaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuarioNombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string materialTitulo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaDesde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaHasta;
        
        public buscarReservasAvanzadoRequest() {
        }
        
        public buscarReservasAvanzadoRequest(string reservaId, string usuarioNombre, string materialTitulo, string estado, string fechaDesde, string fechaHasta) {
            this.reservaId = reservaId;
            this.usuarioNombre = usuarioNombre;
            this.materialTitulo = materialTitulo;
            this.estado = estado;
            this.fechaDesde = fechaDesde;
            this.fechaHasta = fechaHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarReservasAvanzadoResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarReservasAvanzadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.ReservaWS.reservaDTO[] @return;
        
        public buscarReservasAvanzadoResponse() {
        }
        
        public buscarReservasAvanzadoResponse(SoftInvWAProg3.ReservaWS.reservaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerReservaPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerReservaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idReserva;
        
        public obtenerReservaPorIdRequest() {
        }
        
        public obtenerReservaPorIdRequest(int idReserva) {
            this.idReserva = idReserva;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerReservaPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerReservaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.ReservaWS.reservaDTO @return;
        
        public obtenerReservaPorIdResponse() {
        }
        
        public obtenerReservaPorIdResponse(SoftInvWAProg3.ReservaWS.reservaDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReservaWSChannel : SoftInvWAProg3.ReservaWS.ReservaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaWSClient : System.ServiceModel.ClientBase<SoftInvWAProg3.ReservaWS.ReservaWS>, SoftInvWAProg3.ReservaWS.ReservaWS {
        
        public ReservaWSClient() {
        }
        
        public ReservaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaResponse SoftInvWAProg3.ReservaWS.ReservaWS.calcularFechaVencimientoReserva(SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaRequest request) {
            return base.Channel.calcularFechaVencimientoReserva(request);
        }
        
        public System.DateTime calcularFechaVencimientoReserva(System.DateTime fechaReserva, int bibliotecaId) {
            SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaRequest inValue = new SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaRequest();
            inValue.fechaReserva = fechaReserva;
            inValue.bibliotecaId = bibliotecaId;
            SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).calcularFechaVencimientoReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaResponse> SoftInvWAProg3.ReservaWS.ReservaWS.calcularFechaVencimientoReservaAsync(SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaRequest request) {
            return base.Channel.calcularFechaVencimientoReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaResponse> calcularFechaVencimientoReservaAsync(System.DateTime fechaReserva, int bibliotecaId) {
            SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaRequest inValue = new SoftInvWAProg3.ReservaWS.calcularFechaVencimientoReservaRequest();
            inValue.fechaReserva = fechaReserva;
            inValue.bibliotecaId = bibliotecaId;
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).calcularFechaVencimientoReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioResponse SoftInvWAProg3.ReservaWS.ReservaWS.listarReservasVigentesPorUsuario(SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioRequest request) {
            return base.Channel.listarReservasVigentesPorUsuario(request);
        }
        
        public SoftInvWAProg3.ReservaWS.reservaDTO[] listarReservasVigentesPorUsuario(int usuarioId) {
            SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioRequest inValue = new SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioRequest();
            inValue.usuarioId = usuarioId;
            SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).listarReservasVigentesPorUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioResponse> SoftInvWAProg3.ReservaWS.ReservaWS.listarReservasVigentesPorUsuarioAsync(SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioRequest request) {
            return base.Channel.listarReservasVigentesPorUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioResponse> listarReservasVigentesPorUsuarioAsync(int usuarioId) {
            SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioRequest inValue = new SoftInvWAProg3.ReservaWS.listarReservasVigentesPorUsuarioRequest();
            inValue.usuarioId = usuarioId;
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).listarReservasVigentesPorUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.insertarReservaResponse SoftInvWAProg3.ReservaWS.ReservaWS.insertarReserva(SoftInvWAProg3.ReservaWS.insertarReservaRequest request) {
            return base.Channel.insertarReserva(request);
        }
        
        public int insertarReserva(SoftInvWAProg3.ReservaWS.reservaDTO reserva, int bibliotecaId) {
            SoftInvWAProg3.ReservaWS.insertarReservaRequest inValue = new SoftInvWAProg3.ReservaWS.insertarReservaRequest();
            inValue.reserva = reserva;
            inValue.bibliotecaId = bibliotecaId;
            SoftInvWAProg3.ReservaWS.insertarReservaResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).insertarReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.insertarReservaResponse> SoftInvWAProg3.ReservaWS.ReservaWS.insertarReservaAsync(SoftInvWAProg3.ReservaWS.insertarReservaRequest request) {
            return base.Channel.insertarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.insertarReservaResponse> insertarReservaAsync(SoftInvWAProg3.ReservaWS.reservaDTO reserva, int bibliotecaId) {
            SoftInvWAProg3.ReservaWS.insertarReservaRequest inValue = new SoftInvWAProg3.ReservaWS.insertarReservaRequest();
            inValue.reserva = reserva;
            inValue.bibliotecaId = bibliotecaId;
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).insertarReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.modificarReservaResponse SoftInvWAProg3.ReservaWS.ReservaWS.modificarReserva(SoftInvWAProg3.ReservaWS.modificarReservaRequest request) {
            return base.Channel.modificarReserva(request);
        }
        
        public int modificarReserva(SoftInvWAProg3.ReservaWS.reservaDTO reserva) {
            SoftInvWAProg3.ReservaWS.modificarReservaRequest inValue = new SoftInvWAProg3.ReservaWS.modificarReservaRequest();
            inValue.reserva = reserva;
            SoftInvWAProg3.ReservaWS.modificarReservaResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).modificarReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.modificarReservaResponse> SoftInvWAProg3.ReservaWS.ReservaWS.modificarReservaAsync(SoftInvWAProg3.ReservaWS.modificarReservaRequest request) {
            return base.Channel.modificarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.modificarReservaResponse> modificarReservaAsync(SoftInvWAProg3.ReservaWS.reservaDTO reserva) {
            SoftInvWAProg3.ReservaWS.modificarReservaRequest inValue = new SoftInvWAProg3.ReservaWS.modificarReservaRequest();
            inValue.reserva = reserva;
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).modificarReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.eliminarReservaResponse SoftInvWAProg3.ReservaWS.ReservaWS.eliminarReserva(SoftInvWAProg3.ReservaWS.eliminarReservaRequest request) {
            return base.Channel.eliminarReserva(request);
        }
        
        public int eliminarReserva(int idReserva) {
            SoftInvWAProg3.ReservaWS.eliminarReservaRequest inValue = new SoftInvWAProg3.ReservaWS.eliminarReservaRequest();
            inValue.idReserva = idReserva;
            SoftInvWAProg3.ReservaWS.eliminarReservaResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).eliminarReserva(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.eliminarReservaResponse> SoftInvWAProg3.ReservaWS.ReservaWS.eliminarReservaAsync(SoftInvWAProg3.ReservaWS.eliminarReservaRequest request) {
            return base.Channel.eliminarReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.eliminarReservaResponse> eliminarReservaAsync(int idReserva) {
            SoftInvWAProg3.ReservaWS.eliminarReservaRequest inValue = new SoftInvWAProg3.ReservaWS.eliminarReservaRequest();
            inValue.idReserva = idReserva;
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).eliminarReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.listarTodasReservasResponse SoftInvWAProg3.ReservaWS.ReservaWS.listarTodasReservas(SoftInvWAProg3.ReservaWS.listarTodasReservasRequest request) {
            return base.Channel.listarTodasReservas(request);
        }
        
        public SoftInvWAProg3.ReservaWS.reservaDTO[] listarTodasReservas() {
            SoftInvWAProg3.ReservaWS.listarTodasReservasRequest inValue = new SoftInvWAProg3.ReservaWS.listarTodasReservasRequest();
            SoftInvWAProg3.ReservaWS.listarTodasReservasResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).listarTodasReservas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.listarTodasReservasResponse> SoftInvWAProg3.ReservaWS.ReservaWS.listarTodasReservasAsync(SoftInvWAProg3.ReservaWS.listarTodasReservasRequest request) {
            return base.Channel.listarTodasReservasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.listarTodasReservasResponse> listarTodasReservasAsync() {
            SoftInvWAProg3.ReservaWS.listarTodasReservasRequest inValue = new SoftInvWAProg3.ReservaWS.listarTodasReservasRequest();
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).listarTodasReservasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdResponse SoftInvWAProg3.ReservaWS.ReservaWS.obtenerTipoDeMaterialPorId(SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdRequest request) {
            return base.Channel.obtenerTipoDeMaterialPorId(request);
        }
        
        public string obtenerTipoDeMaterialPorId(int idMaterial) {
            SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdRequest inValue = new SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdRequest();
            inValue.idMaterial = idMaterial;
            SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).obtenerTipoDeMaterialPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdResponse> SoftInvWAProg3.ReservaWS.ReservaWS.obtenerTipoDeMaterialPorIdAsync(SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdRequest request) {
            return base.Channel.obtenerTipoDeMaterialPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdResponse> obtenerTipoDeMaterialPorIdAsync(int idMaterial) {
            SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdRequest inValue = new SoftInvWAProg3.ReservaWS.obtenerTipoDeMaterialPorIdRequest();
            inValue.idMaterial = idMaterial;
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).obtenerTipoDeMaterialPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoResponse SoftInvWAProg3.ReservaWS.ReservaWS.buscarReservasAvanzado(SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoRequest request) {
            return base.Channel.buscarReservasAvanzado(request);
        }
        
        public SoftInvWAProg3.ReservaWS.reservaDTO[] buscarReservasAvanzado(string reservaId, string usuarioNombre, string materialTitulo, string estado, string fechaDesde, string fechaHasta) {
            SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoRequest inValue = new SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoRequest();
            inValue.reservaId = reservaId;
            inValue.usuarioNombre = usuarioNombre;
            inValue.materialTitulo = materialTitulo;
            inValue.estado = estado;
            inValue.fechaDesde = fechaDesde;
            inValue.fechaHasta = fechaHasta;
            SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).buscarReservasAvanzado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoResponse> SoftInvWAProg3.ReservaWS.ReservaWS.buscarReservasAvanzadoAsync(SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoRequest request) {
            return base.Channel.buscarReservasAvanzadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoResponse> buscarReservasAvanzadoAsync(string reservaId, string usuarioNombre, string materialTitulo, string estado, string fechaDesde, string fechaHasta) {
            SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoRequest inValue = new SoftInvWAProg3.ReservaWS.buscarReservasAvanzadoRequest();
            inValue.reservaId = reservaId;
            inValue.usuarioNombre = usuarioNombre;
            inValue.materialTitulo = materialTitulo;
            inValue.estado = estado;
            inValue.fechaDesde = fechaDesde;
            inValue.fechaHasta = fechaHasta;
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).buscarReservasAvanzadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.ReservaWS.obtenerReservaPorIdResponse SoftInvWAProg3.ReservaWS.ReservaWS.obtenerReservaPorId(SoftInvWAProg3.ReservaWS.obtenerReservaPorIdRequest request) {
            return base.Channel.obtenerReservaPorId(request);
        }
        
        public SoftInvWAProg3.ReservaWS.reservaDTO obtenerReservaPorId(int idReserva) {
            SoftInvWAProg3.ReservaWS.obtenerReservaPorIdRequest inValue = new SoftInvWAProg3.ReservaWS.obtenerReservaPorIdRequest();
            inValue.idReserva = idReserva;
            SoftInvWAProg3.ReservaWS.obtenerReservaPorIdResponse retVal = ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).obtenerReservaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.obtenerReservaPorIdResponse> SoftInvWAProg3.ReservaWS.ReservaWS.obtenerReservaPorIdAsync(SoftInvWAProg3.ReservaWS.obtenerReservaPorIdRequest request) {
            return base.Channel.obtenerReservaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.ReservaWS.obtenerReservaPorIdResponse> obtenerReservaPorIdAsync(int idReserva) {
            SoftInvWAProg3.ReservaWS.obtenerReservaPorIdRequest inValue = new SoftInvWAProg3.ReservaWS.obtenerReservaPorIdRequest();
            inValue.idReserva = idReserva;
            return ((SoftInvWAProg3.ReservaWS.ReservaWS)(this)).obtenerReservaPorIdAsync(inValue);
        }
    }
}
