//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvWAProg3.BibliotecaWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class bibliotecaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bibliotecaIdField;
        
        private bool bibliotecaIdFieldSpecified;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int bibliotecaId {
            get {
                return this.bibliotecaIdField;
            }
            set {
                this.bibliotecaIdField = value;
                this.RaisePropertyChanged("bibliotecaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bibliotecaIdSpecified {
            get {
                return this.bibliotecaIdFieldSpecified;
            }
            set {
                this.bibliotecaIdFieldSpecified = value;
                this.RaisePropertyChanged("bibliotecaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", ConfigurationName="BibliotecaWS.BibliotecaWS")]
    public interface BibliotecaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecaPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecaPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.BibliotecaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecaPorId/Fault/SQLExcept" +
            "ion", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdResponse obtenerBibliotecaPorId(SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecaPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecaPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdResponse> obtenerBibliotecaPorIdAsync(SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/listarBibliotecasRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/BibliotecaWS/listarBibliotecasResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.BibliotecaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/listarBibliotecas/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.BibliotecaWS.listarBibliotecasResponse listarBibliotecas(SoftInvWAProg3.BibliotecaWS.listarBibliotecasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/listarBibliotecasRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/BibliotecaWS/listarBibliotecasResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.listarBibliotecasResponse> listarBibliotecasAsync(SoftInvWAProg3.BibliotecaWS.listarBibliotecasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecasPorMaterialRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecasPorMaterialResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.BibliotecaWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecasPorMaterial/Fault/SQ" +
            "LException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialResponse obtenerBibliotecasPorMaterial(SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecasPorMaterialRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/BibliotecaWS/obtenerBibliotecasPorMaterialResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialResponse> obtenerBibliotecasPorMaterialAsync(SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBibliotecaPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerBibliotecaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int bibliotecaId;
        
        public obtenerBibliotecaPorIdRequest() {
        }
        
        public obtenerBibliotecaPorIdRequest(int bibliotecaId) {
            this.bibliotecaId = bibliotecaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBibliotecaPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerBibliotecaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.BibliotecaWS.bibliotecaDTO @return;
        
        public obtenerBibliotecaPorIdResponse() {
        }
        
        public obtenerBibliotecaPorIdResponse(SoftInvWAProg3.BibliotecaWS.bibliotecaDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarBibliotecas", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarBibliotecasRequest {
        
        public listarBibliotecasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarBibliotecasResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarBibliotecasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.BibliotecaWS.bibliotecaDTO[] @return;
        
        public listarBibliotecasResponse() {
        }
        
        public listarBibliotecasResponse(SoftInvWAProg3.BibliotecaWS.bibliotecaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBibliotecasPorMaterial", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerBibliotecasPorMaterialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerBibliotecasPorMaterialRequest() {
        }
        
        public obtenerBibliotecasPorMaterialRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerBibliotecasPorMaterialResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerBibliotecasPorMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.BibliotecaWS.bibliotecaDTO[] @return;
        
        public obtenerBibliotecasPorMaterialResponse() {
        }
        
        public obtenerBibliotecasPorMaterialResponse(SoftInvWAProg3.BibliotecaWS.bibliotecaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BibliotecaWSChannel : SoftInvWAProg3.BibliotecaWS.BibliotecaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BibliotecaWSClient : System.ServiceModel.ClientBase<SoftInvWAProg3.BibliotecaWS.BibliotecaWS>, SoftInvWAProg3.BibliotecaWS.BibliotecaWS {
        
        public BibliotecaWSClient() {
        }
        
        public BibliotecaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BibliotecaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibliotecaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BibliotecaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdResponse SoftInvWAProg3.BibliotecaWS.BibliotecaWS.obtenerBibliotecaPorId(SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdRequest request) {
            return base.Channel.obtenerBibliotecaPorId(request);
        }
        
        public SoftInvWAProg3.BibliotecaWS.bibliotecaDTO obtenerBibliotecaPorId(int bibliotecaId) {
            SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdRequest inValue = new SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdRequest();
            inValue.bibliotecaId = bibliotecaId;
            SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdResponse retVal = ((SoftInvWAProg3.BibliotecaWS.BibliotecaWS)(this)).obtenerBibliotecaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdResponse> SoftInvWAProg3.BibliotecaWS.BibliotecaWS.obtenerBibliotecaPorIdAsync(SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdRequest request) {
            return base.Channel.obtenerBibliotecaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdResponse> obtenerBibliotecaPorIdAsync(int bibliotecaId) {
            SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdRequest inValue = new SoftInvWAProg3.BibliotecaWS.obtenerBibliotecaPorIdRequest();
            inValue.bibliotecaId = bibliotecaId;
            return ((SoftInvWAProg3.BibliotecaWS.BibliotecaWS)(this)).obtenerBibliotecaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.BibliotecaWS.listarBibliotecasResponse SoftInvWAProg3.BibliotecaWS.BibliotecaWS.listarBibliotecas(SoftInvWAProg3.BibliotecaWS.listarBibliotecasRequest request) {
            return base.Channel.listarBibliotecas(request);
        }
        
        public SoftInvWAProg3.BibliotecaWS.bibliotecaDTO[] listarBibliotecas() {
            SoftInvWAProg3.BibliotecaWS.listarBibliotecasRequest inValue = new SoftInvWAProg3.BibliotecaWS.listarBibliotecasRequest();
            SoftInvWAProg3.BibliotecaWS.listarBibliotecasResponse retVal = ((SoftInvWAProg3.BibliotecaWS.BibliotecaWS)(this)).listarBibliotecas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.listarBibliotecasResponse> SoftInvWAProg3.BibliotecaWS.BibliotecaWS.listarBibliotecasAsync(SoftInvWAProg3.BibliotecaWS.listarBibliotecasRequest request) {
            return base.Channel.listarBibliotecasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.listarBibliotecasResponse> listarBibliotecasAsync() {
            SoftInvWAProg3.BibliotecaWS.listarBibliotecasRequest inValue = new SoftInvWAProg3.BibliotecaWS.listarBibliotecasRequest();
            return ((SoftInvWAProg3.BibliotecaWS.BibliotecaWS)(this)).listarBibliotecasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialResponse SoftInvWAProg3.BibliotecaWS.BibliotecaWS.obtenerBibliotecasPorMaterial(SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialRequest request) {
            return base.Channel.obtenerBibliotecasPorMaterial(request);
        }
        
        public SoftInvWAProg3.BibliotecaWS.bibliotecaDTO[] obtenerBibliotecasPorMaterial(int id) {
            SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialRequest inValue = new SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialRequest();
            inValue.id = id;
            SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialResponse retVal = ((SoftInvWAProg3.BibliotecaWS.BibliotecaWS)(this)).obtenerBibliotecasPorMaterial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialResponse> SoftInvWAProg3.BibliotecaWS.BibliotecaWS.obtenerBibliotecasPorMaterialAsync(SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialRequest request) {
            return base.Channel.obtenerBibliotecasPorMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialResponse> obtenerBibliotecasPorMaterialAsync(int id) {
            SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialRequest inValue = new SoftInvWAProg3.BibliotecaWS.obtenerBibliotecasPorMaterialRequest();
            inValue.id = id;
            return ((SoftInvWAProg3.BibliotecaWS.BibliotecaWS)(this)).obtenerBibliotecasPorMaterialAsync(inValue);
        }
    }
}
