//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvWAProg3.CirculacionWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class ParseException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorOffsetField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorOffset {
            get {
                return this.errorOffsetField;
            }
            set {
                this.errorOffsetField = value;
                this.RaisePropertyChanged("errorOffset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class tipoUsuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int numeroMaxDiasField;
        
        private bool numeroMaxDiasFieldSpecified;
        
        private int numeroMaxItemsField;
        
        private bool numeroMaxItemsFieldSpecified;
        
        private int tipoUsuarioIdField;
        
        private bool tipoUsuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroMaxDias {
            get {
                return this.numeroMaxDiasField;
            }
            set {
                this.numeroMaxDiasField = value;
                this.RaisePropertyChanged("numeroMaxDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxDiasSpecified {
            get {
                return this.numeroMaxDiasFieldSpecified;
            }
            set {
                this.numeroMaxDiasFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxDiasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroMaxItems {
            get {
                return this.numeroMaxItemsField;
            }
            set {
                this.numeroMaxItemsField = value;
                this.RaisePropertyChanged("numeroMaxItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxItemsSpecified {
            get {
                return this.numeroMaxItemsFieldSpecified;
            }
            set {
                this.numeroMaxItemsFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipoUsuarioId {
            get {
                return this.tipoUsuarioIdField;
            }
            set {
                this.tipoUsuarioIdField = value;
                this.RaisePropertyChanged("tipoUsuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioIdSpecified {
            get {
                return this.tipoUsuarioIdFieldSpecified;
            }
            set {
                this.tipoUsuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoUniversitarioField;
        
        private string correoElectronicoField;
        
        private estadoUsuario estadoField;
        
        private bool estadoFieldSpecified;
        
        private string nombresField;
        
        private string numeroDocumentoField;
        
        private string passwordField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private tipoUsuarioDTO tipoUsuarioField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoUniversitario {
            get {
                return this.codigoUniversitarioField;
            }
            set {
                this.codigoUniversitarioField = value;
                this.RaisePropertyChanged("codigoUniversitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoUsuario estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public tipoUsuarioDTO tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoUsuario {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        SANCIONADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        PASAPORTE,
        
        /// <remarks/>
        CARNET_DE_EXTRANJERIA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class reservaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoReserva estadoReservaField;
        
        private bool estadoReservaFieldSpecified;
        
        private System.DateTime fechaReservaField;
        
        private bool fechaReservaFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private materialDTO materialField;
        
        private int reservaIdField;
        
        private bool reservaIdFieldSpecified;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoReserva estadoReserva {
            get {
                return this.estadoReservaField;
            }
            set {
                this.estadoReservaField = value;
                this.RaisePropertyChanged("estadoReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoReservaSpecified {
            get {
                return this.estadoReservaFieldSpecified;
            }
            set {
                this.estadoReservaFieldSpecified = value;
                this.RaisePropertyChanged("estadoReservaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fechaReserva {
            get {
                return this.fechaReservaField;
            }
            set {
                this.fechaReservaField = value;
                this.RaisePropertyChanged("fechaReserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaReservaSpecified {
            get {
                return this.fechaReservaFieldSpecified;
            }
            set {
                this.fechaReservaFieldSpecified = value;
                this.RaisePropertyChanged("fechaReservaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public materialDTO material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int reservaId {
            get {
                return this.reservaIdField;
            }
            set {
                this.reservaIdField = value;
                this.RaisePropertyChanged("reservaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reservaIdSpecified {
            get {
                return this.reservaIdFieldSpecified;
            }
            set {
                this.reservaIdFieldSpecified = value;
                this.RaisePropertyChanged("reservaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoReserva {
        
        /// <remarks/>
        VIGENTE,
        
        /// <remarks/>
        VENCIDA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class materialDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anioPublicacionField;
        
        private bool anioPublicacionFieldSpecified;
        
        private string autorField;
        
        private string idiomaField;
        
        private int materialIdField;
        
        private bool materialIdFieldSpecified;
        
        private int numeroPaginasField;
        
        private bool numeroPaginasFieldSpecified;
        
        private string temaField;
        
        private tipoMaterial tipoMaterialField;
        
        private bool tipoMaterialFieldSpecified;
        
        private string tituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anioPublicacion {
            get {
                return this.anioPublicacionField;
            }
            set {
                this.anioPublicacionField = value;
                this.RaisePropertyChanged("anioPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anioPublicacionSpecified {
            get {
                return this.anioPublicacionFieldSpecified;
            }
            set {
                this.anioPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("anioPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int materialId {
            get {
                return this.materialIdField;
            }
            set {
                this.materialIdField = value;
                this.RaisePropertyChanged("materialId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool materialIdSpecified {
            get {
                return this.materialIdFieldSpecified;
            }
            set {
                this.materialIdFieldSpecified = value;
                this.RaisePropertyChanged("materialIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroPaginas {
            get {
                return this.numeroPaginasField;
            }
            set {
                this.numeroPaginasField = value;
                this.RaisePropertyChanged("numeroPaginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroPaginasSpecified {
            get {
                return this.numeroPaginasFieldSpecified;
            }
            set {
                this.numeroPaginasFieldSpecified = value;
                this.RaisePropertyChanged("numeroPaginasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tema {
            get {
                return this.temaField;
            }
            set {
                this.temaField = value;
                this.RaisePropertyChanged("tema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipoMaterial tipoMaterial {
            get {
                return this.tipoMaterialField;
            }
            set {
                this.tipoMaterialField = value;
                this.RaisePropertyChanged("tipoMaterial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoMaterialSpecified {
            get {
                return this.tipoMaterialFieldSpecified;
            }
            set {
                this.tipoMaterialFieldSpecified = value;
                this.RaisePropertyChanged("tipoMaterialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum tipoMaterial {
        
        /// <remarks/>
        LIBRO,
        
        /// <remarks/>
        ARTICULO,
        
        /// <remarks/>
        TESIS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class bibliotecaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bibliotecaIdField;
        
        private bool bibliotecaIdFieldSpecified;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int bibliotecaId {
            get {
                return this.bibliotecaIdField;
            }
            set {
                this.bibliotecaIdField = value;
                this.RaisePropertyChanged("bibliotecaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bibliotecaIdSpecified {
            get {
                return this.bibliotecaIdFieldSpecified;
            }
            set {
                this.bibliotecaIdFieldSpecified = value;
                this.RaisePropertyChanged("bibliotecaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class ejemplarDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bibliotecaDTO bibliotecaField;
        
        private int ejemplarIdField;
        
        private bool ejemplarIdFieldSpecified;
        
        private bool eliminableField;
        
        private bool eliminableFieldSpecified;
        
        private estadoEjemplar estadoField;
        
        private bool estadoFieldSpecified;
        
        private string locacionEnBibliotecaField;
        
        private materialDTO materialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bibliotecaDTO biblioteca {
            get {
                return this.bibliotecaField;
            }
            set {
                this.bibliotecaField = value;
                this.RaisePropertyChanged("biblioteca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ejemplarId {
            get {
                return this.ejemplarIdField;
            }
            set {
                this.ejemplarIdField = value;
                this.RaisePropertyChanged("ejemplarId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ejemplarIdSpecified {
            get {
                return this.ejemplarIdFieldSpecified;
            }
            set {
                this.ejemplarIdFieldSpecified = value;
                this.RaisePropertyChanged("ejemplarIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool eliminable {
            get {
                return this.eliminableField;
            }
            set {
                this.eliminableField = value;
                this.RaisePropertyChanged("eliminable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eliminableSpecified {
            get {
                return this.eliminableFieldSpecified;
            }
            set {
                this.eliminableFieldSpecified = value;
                this.RaisePropertyChanged("eliminableSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public estadoEjemplar estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string locacionEnBiblioteca {
            get {
                return this.locacionEnBibliotecaField;
            }
            set {
                this.locacionEnBibliotecaField = value;
                this.RaisePropertyChanged("locacionEnBiblioteca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public materialDTO material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
                this.RaisePropertyChanged("material");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoEjemplar {
        
        /// <remarks/>
        DISPONIBLE,
        
        /// <remarks/>
        PRESTADO,
        
        /// <remarks/>
        EN_REPARACION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class circulacionDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int circulacionIdField;
        
        private bool circulacionIdFieldSpecified;
        
        private ejemplarDTO ejemplarField;
        
        private estadoPrestamo estadoPrestamoField;
        
        private bool estadoPrestamoFieldSpecified;
        
        private System.DateTime fechaDevolucionField;
        
        private bool fechaDevolucionFieldSpecified;
        
        private System.DateTime fechaPrestamoField;
        
        private bool fechaPrestamoFieldSpecified;
        
        private System.DateTime fechaVencimientoField;
        
        private bool fechaVencimientoFieldSpecified;
        
        private reservaDTO reservaField;
        
        private usuarioDTO usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int circulacionId {
            get {
                return this.circulacionIdField;
            }
            set {
                this.circulacionIdField = value;
                this.RaisePropertyChanged("circulacionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool circulacionIdSpecified {
            get {
                return this.circulacionIdFieldSpecified;
            }
            set {
                this.circulacionIdFieldSpecified = value;
                this.RaisePropertyChanged("circulacionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ejemplarDTO ejemplar {
            get {
                return this.ejemplarField;
            }
            set {
                this.ejemplarField = value;
                this.RaisePropertyChanged("ejemplar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoPrestamo estadoPrestamo {
            get {
                return this.estadoPrestamoField;
            }
            set {
                this.estadoPrestamoField = value;
                this.RaisePropertyChanged("estadoPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoPrestamoSpecified {
            get {
                return this.estadoPrestamoFieldSpecified;
            }
            set {
                this.estadoPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("estadoPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaDevolucion {
            get {
                return this.fechaDevolucionField;
            }
            set {
                this.fechaDevolucionField = value;
                this.RaisePropertyChanged("fechaDevolucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaDevolucionSpecified {
            get {
                return this.fechaDevolucionFieldSpecified;
            }
            set {
                this.fechaDevolucionFieldSpecified = value;
                this.RaisePropertyChanged("fechaDevolucionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaPrestamo {
            get {
                return this.fechaPrestamoField;
            }
            set {
                this.fechaPrestamoField = value;
                this.RaisePropertyChanged("fechaPrestamo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPrestamoSpecified {
            get {
                return this.fechaPrestamoFieldSpecified;
            }
            set {
                this.fechaPrestamoFieldSpecified = value;
                this.RaisePropertyChanged("fechaPrestamoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
                this.RaisePropertyChanged("fechaVencimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaVencimientoSpecified {
            get {
                return this.fechaVencimientoFieldSpecified;
            }
            set {
                this.fechaVencimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaVencimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public reservaDTO reserva {
            get {
                return this.reservaField;
            }
            set {
                this.reservaField = value;
                this.RaisePropertyChanged("reserva");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public usuarioDTO usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoPrestamo {
        
        /// <remarks/>
        VIGENTE,
        
        /// <remarks/>
        DEVUELTO_A_TIEMPO,
        
        /// <remarks/>
        DEVUELTO_CON_RETRASO,
        
        /// <remarks/>
        DEVUELTO_DANADO_O_PERDIDO,
        
        /// <remarks/>
        DEVUELTO_RETRASO_Y_DANO_PERDIDA,
        
        /// <remarks/>
        NO_DEVUELTO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", ConfigurationName="CirculacionWS.CirculacionWS")]
    public interface CirculacionWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/buscarCirculacionesAvanzadoRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/buscarCirculacionesAvanzadoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.CirculacionWS.ParseException), Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/buscarCirculacionesAvanzado/Fault/Par" +
            "seException", Name="ParseException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.CirculacionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/buscarCirculacionesAvanzado/Fault/SQL" +
            "Exception", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoResponse buscarCirculacionesAvanzado(SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/buscarCirculacionesAvanzadoRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/buscarCirculacionesAvanzadoResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoResponse> buscarCirculacionesAvanzadoAsync(SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarTodasCirculacionesRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarTodasCirculacionesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.CirculacionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarTodasCirculaciones/Fault/SQLExc" +
            "eption", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesResponse listarTodasCirculaciones(SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarTodasCirculacionesRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarTodasCirculacionesResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesResponse> listarTodasCirculacionesAsync(SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/insertarCirculacionRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/insertarCirculacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.CirculacionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/insertarCirculacion/Fault/SQLExceptio" +
            "n", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.CirculacionWS.insertarCirculacionResponse insertarCirculacion(SoftInvWAProg3.CirculacionWS.insertarCirculacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/insertarCirculacionRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/insertarCirculacionResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.insertarCirculacionResponse> insertarCirculacionAsync(SoftInvWAProg3.CirculacionWS.insertarCirculacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/obtenerCirculacionPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/obtenerCirculacionPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.CirculacionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/obtenerCirculacionPorId/Fault/SQLExce" +
            "ption", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdResponse obtenerCirculacionPorId(SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/obtenerCirculacionPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/obtenerCirculacionPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdResponse> obtenerCirculacionPorIdAsync(SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarPrestamosPorUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarPrestamosPorUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.CirculacionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarPrestamosPorUsuario/Fault/SQLEx" +
            "ception", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioResponse listarPrestamosPorUsuario(SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarPrestamosPorUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/listarPrestamosPorUsuarioResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioResponse> listarPrestamosPorUsuarioAsync(SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/modificarCirculacionRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/modificarCirculacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.CirculacionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/modificarCirculacion/Fault/SQLExcepti" +
            "on", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.CirculacionWS.modificarCirculacionResponse modificarCirculacion(SoftInvWAProg3.CirculacionWS.modificarCirculacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/modificarCirculacionRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/modificarCirculacionResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.modificarCirculacionResponse> modificarCirculacionAsync(SoftInvWAProg3.CirculacionWS.modificarCirculacionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/eliminarCirculacionRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/eliminarCirculacionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.CirculacionWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/eliminarCirculacion/Fault/SQLExceptio" +
            "n", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.CirculacionWS.eliminarCirculacionResponse eliminarCirculacion(SoftInvWAProg3.CirculacionWS.eliminarCirculacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/CirculacionWS/eliminarCirculacionRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/CirculacionWS/eliminarCirculacionResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.eliminarCirculacionResponse> eliminarCirculacionAsync(SoftInvWAProg3.CirculacionWS.eliminarCirculacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarCirculacionesAvanzado", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarCirculacionesAvanzadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idCirculacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idReserva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idEjemplar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaDesde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaHasta;
        
        public buscarCirculacionesAvanzadoRequest() {
        }
        
        public buscarCirculacionesAvanzadoRequest(string idCirculacion, string idReserva, string idUsuario, string idEjemplar, string estado, string fechaDesde, string fechaHasta) {
            this.idCirculacion = idCirculacion;
            this.idReserva = idReserva;
            this.idUsuario = idUsuario;
            this.idEjemplar = idEjemplar;
            this.estado = estado;
            this.fechaDesde = fechaDesde;
            this.fechaHasta = fechaHasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarCirculacionesAvanzadoResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarCirculacionesAvanzadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.CirculacionWS.circulacionDTO[] @return;
        
        public buscarCirculacionesAvanzadoResponse() {
        }
        
        public buscarCirculacionesAvanzadoResponse(SoftInvWAProg3.CirculacionWS.circulacionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasCirculaciones", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasCirculacionesRequest {
        
        public listarTodasCirculacionesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasCirculacionesResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasCirculacionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.CirculacionWS.circulacionDTO[] @return;
        
        public listarTodasCirculacionesResponse() {
        }
        
        public listarTodasCirculacionesResponse(SoftInvWAProg3.CirculacionWS.circulacionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCirculacion", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCirculacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.CirculacionWS.circulacionDTO circulacion;
        
        public insertarCirculacionRequest() {
        }
        
        public insertarCirculacionRequest(SoftInvWAProg3.CirculacionWS.circulacionDTO circulacion) {
            this.circulacion = circulacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarCirculacionResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarCirculacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarCirculacionResponse() {
        }
        
        public insertarCirculacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCirculacionPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCirculacionPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCirculacion;
        
        public obtenerCirculacionPorIdRequest() {
        }
        
        public obtenerCirculacionPorIdRequest(int idCirculacion) {
            this.idCirculacion = idCirculacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerCirculacionPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerCirculacionPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.CirculacionWS.circulacionDTO @return;
        
        public obtenerCirculacionPorIdResponse() {
        }
        
        public obtenerCirculacionPorIdResponse(SoftInvWAProg3.CirculacionWS.circulacionDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosPorUsuario", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPrestamosPorUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int usuarioId;
        
        public listarPrestamosPorUsuarioRequest() {
        }
        
        public listarPrestamosPorUsuarioRequest(int usuarioId) {
            this.usuarioId = usuarioId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPrestamosPorUsuarioResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPrestamosPorUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.CirculacionWS.circulacionDTO[] @return;
        
        public listarPrestamosPorUsuarioResponse() {
        }
        
        public listarPrestamosPorUsuarioResponse(SoftInvWAProg3.CirculacionWS.circulacionDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCirculacion", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCirculacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.CirculacionWS.circulacionDTO circulacion;
        
        public modificarCirculacionRequest() {
        }
        
        public modificarCirculacionRequest(SoftInvWAProg3.CirculacionWS.circulacionDTO circulacion) {
            this.circulacion = circulacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarCirculacionResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarCirculacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarCirculacionResponse() {
        }
        
        public modificarCirculacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCirculacion", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCirculacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCirculacion;
        
        public eliminarCirculacionRequest() {
        }
        
        public eliminarCirculacionRequest(int idCirculacion) {
            this.idCirculacion = idCirculacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarCirculacionResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarCirculacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarCirculacionResponse() {
        }
        
        public eliminarCirculacionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CirculacionWSChannel : SoftInvWAProg3.CirculacionWS.CirculacionWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CirculacionWSClient : System.ServiceModel.ClientBase<SoftInvWAProg3.CirculacionWS.CirculacionWS>, SoftInvWAProg3.CirculacionWS.CirculacionWS {
        
        public CirculacionWSClient() {
        }
        
        public CirculacionWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CirculacionWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CirculacionWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CirculacionWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoResponse SoftInvWAProg3.CirculacionWS.CirculacionWS.buscarCirculacionesAvanzado(SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoRequest request) {
            return base.Channel.buscarCirculacionesAvanzado(request);
        }
        
        public SoftInvWAProg3.CirculacionWS.circulacionDTO[] buscarCirculacionesAvanzado(string idCirculacion, string idReserva, string idUsuario, string idEjemplar, string estado, string fechaDesde, string fechaHasta) {
            SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoRequest inValue = new SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoRequest();
            inValue.idCirculacion = idCirculacion;
            inValue.idReserva = idReserva;
            inValue.idUsuario = idUsuario;
            inValue.idEjemplar = idEjemplar;
            inValue.estado = estado;
            inValue.fechaDesde = fechaDesde;
            inValue.fechaHasta = fechaHasta;
            SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoResponse retVal = ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).buscarCirculacionesAvanzado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoResponse> SoftInvWAProg3.CirculacionWS.CirculacionWS.buscarCirculacionesAvanzadoAsync(SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoRequest request) {
            return base.Channel.buscarCirculacionesAvanzadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoResponse> buscarCirculacionesAvanzadoAsync(string idCirculacion, string idReserva, string idUsuario, string idEjemplar, string estado, string fechaDesde, string fechaHasta) {
            SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoRequest inValue = new SoftInvWAProg3.CirculacionWS.buscarCirculacionesAvanzadoRequest();
            inValue.idCirculacion = idCirculacion;
            inValue.idReserva = idReserva;
            inValue.idUsuario = idUsuario;
            inValue.idEjemplar = idEjemplar;
            inValue.estado = estado;
            inValue.fechaDesde = fechaDesde;
            inValue.fechaHasta = fechaHasta;
            return ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).buscarCirculacionesAvanzadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesResponse SoftInvWAProg3.CirculacionWS.CirculacionWS.listarTodasCirculaciones(SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesRequest request) {
            return base.Channel.listarTodasCirculaciones(request);
        }
        
        public SoftInvWAProg3.CirculacionWS.circulacionDTO[] listarTodasCirculaciones() {
            SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesRequest inValue = new SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesRequest();
            SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesResponse retVal = ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).listarTodasCirculaciones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesResponse> SoftInvWAProg3.CirculacionWS.CirculacionWS.listarTodasCirculacionesAsync(SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesRequest request) {
            return base.Channel.listarTodasCirculacionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesResponse> listarTodasCirculacionesAsync() {
            SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesRequest inValue = new SoftInvWAProg3.CirculacionWS.listarTodasCirculacionesRequest();
            return ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).listarTodasCirculacionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.CirculacionWS.insertarCirculacionResponse SoftInvWAProg3.CirculacionWS.CirculacionWS.insertarCirculacion(SoftInvWAProg3.CirculacionWS.insertarCirculacionRequest request) {
            return base.Channel.insertarCirculacion(request);
        }
        
        public int insertarCirculacion(SoftInvWAProg3.CirculacionWS.circulacionDTO circulacion) {
            SoftInvWAProg3.CirculacionWS.insertarCirculacionRequest inValue = new SoftInvWAProg3.CirculacionWS.insertarCirculacionRequest();
            inValue.circulacion = circulacion;
            SoftInvWAProg3.CirculacionWS.insertarCirculacionResponse retVal = ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).insertarCirculacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.insertarCirculacionResponse> SoftInvWAProg3.CirculacionWS.CirculacionWS.insertarCirculacionAsync(SoftInvWAProg3.CirculacionWS.insertarCirculacionRequest request) {
            return base.Channel.insertarCirculacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.insertarCirculacionResponse> insertarCirculacionAsync(SoftInvWAProg3.CirculacionWS.circulacionDTO circulacion) {
            SoftInvWAProg3.CirculacionWS.insertarCirculacionRequest inValue = new SoftInvWAProg3.CirculacionWS.insertarCirculacionRequest();
            inValue.circulacion = circulacion;
            return ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).insertarCirculacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdResponse SoftInvWAProg3.CirculacionWS.CirculacionWS.obtenerCirculacionPorId(SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdRequest request) {
            return base.Channel.obtenerCirculacionPorId(request);
        }
        
        public SoftInvWAProg3.CirculacionWS.circulacionDTO obtenerCirculacionPorId(int idCirculacion) {
            SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdRequest inValue = new SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdRequest();
            inValue.idCirculacion = idCirculacion;
            SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdResponse retVal = ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).obtenerCirculacionPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdResponse> SoftInvWAProg3.CirculacionWS.CirculacionWS.obtenerCirculacionPorIdAsync(SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdRequest request) {
            return base.Channel.obtenerCirculacionPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdResponse> obtenerCirculacionPorIdAsync(int idCirculacion) {
            SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdRequest inValue = new SoftInvWAProg3.CirculacionWS.obtenerCirculacionPorIdRequest();
            inValue.idCirculacion = idCirculacion;
            return ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).obtenerCirculacionPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioResponse SoftInvWAProg3.CirculacionWS.CirculacionWS.listarPrestamosPorUsuario(SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioRequest request) {
            return base.Channel.listarPrestamosPorUsuario(request);
        }
        
        public SoftInvWAProg3.CirculacionWS.circulacionDTO[] listarPrestamosPorUsuario(int usuarioId) {
            SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioRequest inValue = new SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioRequest();
            inValue.usuarioId = usuarioId;
            SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioResponse retVal = ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).listarPrestamosPorUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioResponse> SoftInvWAProg3.CirculacionWS.CirculacionWS.listarPrestamosPorUsuarioAsync(SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioRequest request) {
            return base.Channel.listarPrestamosPorUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioResponse> listarPrestamosPorUsuarioAsync(int usuarioId) {
            SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioRequest inValue = new SoftInvWAProg3.CirculacionWS.listarPrestamosPorUsuarioRequest();
            inValue.usuarioId = usuarioId;
            return ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).listarPrestamosPorUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.CirculacionWS.modificarCirculacionResponse SoftInvWAProg3.CirculacionWS.CirculacionWS.modificarCirculacion(SoftInvWAProg3.CirculacionWS.modificarCirculacionRequest request) {
            return base.Channel.modificarCirculacion(request);
        }
        
        public int modificarCirculacion(SoftInvWAProg3.CirculacionWS.circulacionDTO circulacion) {
            SoftInvWAProg3.CirculacionWS.modificarCirculacionRequest inValue = new SoftInvWAProg3.CirculacionWS.modificarCirculacionRequest();
            inValue.circulacion = circulacion;
            SoftInvWAProg3.CirculacionWS.modificarCirculacionResponse retVal = ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).modificarCirculacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.modificarCirculacionResponse> SoftInvWAProg3.CirculacionWS.CirculacionWS.modificarCirculacionAsync(SoftInvWAProg3.CirculacionWS.modificarCirculacionRequest request) {
            return base.Channel.modificarCirculacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.modificarCirculacionResponse> modificarCirculacionAsync(SoftInvWAProg3.CirculacionWS.circulacionDTO circulacion) {
            SoftInvWAProg3.CirculacionWS.modificarCirculacionRequest inValue = new SoftInvWAProg3.CirculacionWS.modificarCirculacionRequest();
            inValue.circulacion = circulacion;
            return ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).modificarCirculacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.CirculacionWS.eliminarCirculacionResponse SoftInvWAProg3.CirculacionWS.CirculacionWS.eliminarCirculacion(SoftInvWAProg3.CirculacionWS.eliminarCirculacionRequest request) {
            return base.Channel.eliminarCirculacion(request);
        }
        
        public int eliminarCirculacion(int idCirculacion) {
            SoftInvWAProg3.CirculacionWS.eliminarCirculacionRequest inValue = new SoftInvWAProg3.CirculacionWS.eliminarCirculacionRequest();
            inValue.idCirculacion = idCirculacion;
            SoftInvWAProg3.CirculacionWS.eliminarCirculacionResponse retVal = ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).eliminarCirculacion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.eliminarCirculacionResponse> SoftInvWAProg3.CirculacionWS.CirculacionWS.eliminarCirculacionAsync(SoftInvWAProg3.CirculacionWS.eliminarCirculacionRequest request) {
            return base.Channel.eliminarCirculacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.CirculacionWS.eliminarCirculacionResponse> eliminarCirculacionAsync(int idCirculacion) {
            SoftInvWAProg3.CirculacionWS.eliminarCirculacionRequest inValue = new SoftInvWAProg3.CirculacionWS.eliminarCirculacionRequest();
            inValue.idCirculacion = idCirculacion;
            return ((SoftInvWAProg3.CirculacionWS.CirculacionWS)(this)).eliminarCirculacionAsync(inValue);
        }
    }
}
