//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvWAProg3.TipoUsuarioWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class tipoUsuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int numeroMaxDiasField;
        
        private bool numeroMaxDiasFieldSpecified;
        
        private int numeroMaxItemsField;
        
        private bool numeroMaxItemsFieldSpecified;
        
        private int tipoUsuarioIdField;
        
        private bool tipoUsuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroMaxDias {
            get {
                return this.numeroMaxDiasField;
            }
            set {
                this.numeroMaxDiasField = value;
                this.RaisePropertyChanged("numeroMaxDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxDiasSpecified {
            get {
                return this.numeroMaxDiasFieldSpecified;
            }
            set {
                this.numeroMaxDiasFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxDiasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroMaxItems {
            get {
                return this.numeroMaxItemsField;
            }
            set {
                this.numeroMaxItemsField = value;
                this.RaisePropertyChanged("numeroMaxItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxItemsSpecified {
            get {
                return this.numeroMaxItemsFieldSpecified;
            }
            set {
                this.numeroMaxItemsFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipoUsuarioId {
            get {
                return this.tipoUsuarioIdField;
            }
            set {
                this.tipoUsuarioIdField = value;
                this.RaisePropertyChanged("tipoUsuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioIdSpecified {
            get {
                return this.tipoUsuarioIdFieldSpecified;
            }
            set {
                this.tipoUsuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", ConfigurationName="TipoUsuarioWS.TipoUsuarioWS")]
    public interface TipoUsuarioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/insertarTipoUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/insertarTipoUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.TipoUsuarioWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/insertarTipoUsuario/Fault/SQLExceptio" +
            "n", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioResponse insertarTipoUsuario(SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/insertarTipoUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/insertarTipoUsuarioResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioResponse> insertarTipoUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/modificarTipoUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/modificarTipoUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.TipoUsuarioWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/modificarTipoUsuario/Fault/SQLExcepti" +
            "on", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioResponse modificarTipoUsuario(SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/modificarTipoUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/modificarTipoUsuarioResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioResponse> modificarTipoUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/eliminarTipoUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/eliminarTipoUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.TipoUsuarioWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/eliminarTipoUsuario/Fault/SQLExceptio" +
            "n", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioResponse eliminarTipoUsuario(SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/eliminarTipoUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/eliminarTipoUsuarioResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioResponse> eliminarTipoUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/obtenerTipoUsuarioPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/obtenerTipoUsuarioPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.TipoUsuarioWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/obtenerTipoUsuarioPorId/Fault/SQLExce" +
            "ption", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdResponse obtenerTipoUsuarioPorId(SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/obtenerTipoUsuarioPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/obtenerTipoUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdResponse> obtenerTipoUsuarioPorIdAsync(SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/listarTodosTiposUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/listarTodosTiposUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.TipoUsuarioWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/listarTodosTiposUsuario/Fault/SQLExce" +
            "ption", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioResponse listarTodosTiposUsuario(SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/listarTodosTiposUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/TipoUsuarioWS/listarTodosTiposUsuarioResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioResponse> listarTodosTiposUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoUsuario", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO tipoUsuario;
        
        public insertarTipoUsuarioRequest() {
        }
        
        public insertarTipoUsuarioRequest(SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO tipoUsuario) {
            this.tipoUsuario = tipoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoUsuarioResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTipoUsuarioResponse() {
        }
        
        public insertarTipoUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTipoUsuario", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO tipoUsuario;
        
        public modificarTipoUsuarioRequest() {
        }
        
        public modificarTipoUsuarioRequest(SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO tipoUsuario) {
            this.tipoUsuario = tipoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarTipoUsuarioResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarTipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarTipoUsuarioResponse() {
        }
        
        public modificarTipoUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoUsuario", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoUsuario;
        
        public eliminarTipoUsuarioRequest() {
        }
        
        public eliminarTipoUsuarioRequest(int idTipoUsuario) {
            this.idTipoUsuario = idTipoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoUsuarioResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTipoUsuarioResponse() {
        }
        
        public eliminarTipoUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTipoUsuarioPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerTipoUsuarioPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoUsuario;
        
        public obtenerTipoUsuarioPorIdRequest() {
        }
        
        public obtenerTipoUsuarioPorIdRequest(int idTipoUsuario) {
            this.idTipoUsuario = idTipoUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerTipoUsuarioPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerTipoUsuarioPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO @return;
        
        public obtenerTipoUsuarioPorIdResponse() {
        }
        
        public obtenerTipoUsuarioPorIdResponse(SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTiposUsuario", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTiposUsuarioRequest {
        
        public listarTodosTiposUsuarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTiposUsuarioResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTiposUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO[] @return;
        
        public listarTodosTiposUsuarioResponse() {
        }
        
        public listarTodosTiposUsuarioResponse(SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoUsuarioWSChannel : SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoUsuarioWSClient : System.ServiceModel.ClientBase<SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS>, SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS {
        
        public TipoUsuarioWSClient() {
        }
        
        public TipoUsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoUsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoUsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoUsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioResponse SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.insertarTipoUsuario(SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioRequest request) {
            return base.Channel.insertarTipoUsuario(request);
        }
        
        public int insertarTipoUsuario(SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO tipoUsuario) {
            SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioRequest();
            inValue.tipoUsuario = tipoUsuario;
            SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioResponse retVal = ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).insertarTipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioResponse> SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.insertarTipoUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioRequest request) {
            return base.Channel.insertarTipoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioResponse> insertarTipoUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO tipoUsuario) {
            SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.insertarTipoUsuarioRequest();
            inValue.tipoUsuario = tipoUsuario;
            return ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).insertarTipoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioResponse SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.modificarTipoUsuario(SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioRequest request) {
            return base.Channel.modificarTipoUsuario(request);
        }
        
        public int modificarTipoUsuario(SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO tipoUsuario) {
            SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioRequest();
            inValue.tipoUsuario = tipoUsuario;
            SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioResponse retVal = ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).modificarTipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioResponse> SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.modificarTipoUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioRequest request) {
            return base.Channel.modificarTipoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioResponse> modificarTipoUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO tipoUsuario) {
            SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.modificarTipoUsuarioRequest();
            inValue.tipoUsuario = tipoUsuario;
            return ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).modificarTipoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioResponse SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.eliminarTipoUsuario(SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioRequest request) {
            return base.Channel.eliminarTipoUsuario(request);
        }
        
        public int eliminarTipoUsuario(int idTipoUsuario) {
            SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioRequest();
            inValue.idTipoUsuario = idTipoUsuario;
            SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioResponse retVal = ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).eliminarTipoUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioResponse> SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.eliminarTipoUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioRequest request) {
            return base.Channel.eliminarTipoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioResponse> eliminarTipoUsuarioAsync(int idTipoUsuario) {
            SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.eliminarTipoUsuarioRequest();
            inValue.idTipoUsuario = idTipoUsuario;
            return ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).eliminarTipoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdResponse SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.obtenerTipoUsuarioPorId(SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdRequest request) {
            return base.Channel.obtenerTipoUsuarioPorId(request);
        }
        
        public SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO obtenerTipoUsuarioPorId(int idTipoUsuario) {
            SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdRequest();
            inValue.idTipoUsuario = idTipoUsuario;
            SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdResponse retVal = ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).obtenerTipoUsuarioPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdResponse> SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.obtenerTipoUsuarioPorIdAsync(SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdRequest request) {
            return base.Channel.obtenerTipoUsuarioPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdResponse> obtenerTipoUsuarioPorIdAsync(int idTipoUsuario) {
            SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.obtenerTipoUsuarioPorIdRequest();
            inValue.idTipoUsuario = idTipoUsuario;
            return ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).obtenerTipoUsuarioPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioResponse SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.listarTodosTiposUsuario(SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioRequest request) {
            return base.Channel.listarTodosTiposUsuario(request);
        }
        
        public SoftInvWAProg3.TipoUsuarioWS.tipoUsuarioDTO[] listarTodosTiposUsuario() {
            SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioRequest();
            SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioResponse retVal = ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).listarTodosTiposUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioResponse> SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS.listarTodosTiposUsuarioAsync(SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioRequest request) {
            return base.Channel.listarTodosTiposUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioResponse> listarTodosTiposUsuarioAsync() {
            SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioRequest inValue = new SoftInvWAProg3.TipoUsuarioWS.listarTodosTiposUsuarioRequest();
            return ((SoftInvWAProg3.TipoUsuarioWS.TipoUsuarioWS)(this)).listarTodosTiposUsuarioAsync(inValue);
        }
    }
}
