//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftInvWAProg3.UsuarioWS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class SQLException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sQLStateField;
        
        private int errorCodeField;
        
        private string messageField;
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string SQLState {
            get {
                return this.sQLStateField;
            }
            set {
                this.sQLStateField = value;
                this.RaisePropertyChanged("SQLState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class sqlException : exception {
        
        private sqlException nextExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public sqlException nextException {
            get {
                return this.nextExceptionField;
            }
            set {
                this.nextExceptionField = value;
                this.RaisePropertyChanged("nextException");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class exception : throwable {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(exception))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sqlException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class throwable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private stackTraceElement[] stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stackTrace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public stackTraceElement[] stackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
                this.RaisePropertyChanged("stackTrace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class stackTraceElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class bibliotecaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int bibliotecaIdField;
        
        private bool bibliotecaIdFieldSpecified;
        
        private string nombreField;
        
        private string ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int bibliotecaId {
            get {
                return this.bibliotecaIdField;
            }
            set {
                this.bibliotecaIdField = value;
                this.RaisePropertyChanged("bibliotecaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bibliotecaIdSpecified {
            get {
                return this.bibliotecaIdFieldSpecified;
            }
            set {
                this.bibliotecaIdFieldSpecified = value;
                this.RaisePropertyChanged("bibliotecaIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class tipoUsuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private int numeroMaxDiasField;
        
        private bool numeroMaxDiasFieldSpecified;
        
        private int numeroMaxItemsField;
        
        private bool numeroMaxItemsFieldSpecified;
        
        private int tipoUsuarioIdField;
        
        private bool tipoUsuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroMaxDias {
            get {
                return this.numeroMaxDiasField;
            }
            set {
                this.numeroMaxDiasField = value;
                this.RaisePropertyChanged("numeroMaxDias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxDiasSpecified {
            get {
                return this.numeroMaxDiasFieldSpecified;
            }
            set {
                this.numeroMaxDiasFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxDiasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroMaxItems {
            get {
                return this.numeroMaxItemsField;
            }
            set {
                this.numeroMaxItemsField = value;
                this.RaisePropertyChanged("numeroMaxItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroMaxItemsSpecified {
            get {
                return this.numeroMaxItemsFieldSpecified;
            }
            set {
                this.numeroMaxItemsFieldSpecified = value;
                this.RaisePropertyChanged("numeroMaxItemsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tipoUsuarioId {
            get {
                return this.tipoUsuarioIdField;
            }
            set {
                this.tipoUsuarioIdField = value;
                this.RaisePropertyChanged("tipoUsuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoUsuarioIdSpecified {
            get {
                return this.tipoUsuarioIdFieldSpecified;
            }
            set {
                this.tipoUsuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("tipoUsuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bibliotecarioDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(docenteDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(estudianteDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class usuarioDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoUniversitarioField;
        
        private string correoElectronicoField;
        
        private estadoUsuario estadoField;
        
        private bool estadoFieldSpecified;
        
        private string nombresField;
        
        private string numeroDocumentoField;
        
        private string passwordField;
        
        private string primerApellidoField;
        
        private string segundoApellidoField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        private tipoUsuarioDTO tipoUsuarioField;
        
        private int usuarioIdField;
        
        private bool usuarioIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoUniversitario {
            get {
                return this.codigoUniversitarioField;
            }
            set {
                this.codigoUniversitarioField = value;
                this.RaisePropertyChanged("codigoUniversitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correoElectronico {
            get {
                return this.correoElectronicoField;
            }
            set {
                this.correoElectronicoField = value;
                this.RaisePropertyChanged("correoElectronico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoUsuario estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public tipoUsuarioDTO tipoUsuario {
            get {
                return this.tipoUsuarioField;
            }
            set {
                this.tipoUsuarioField = value;
                this.RaisePropertyChanged("tipoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int usuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
                this.RaisePropertyChanged("usuarioId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usuarioIdSpecified {
            get {
                return this.usuarioIdFieldSpecified;
            }
            set {
                this.usuarioIdFieldSpecified = value;
                this.RaisePropertyChanged("usuarioIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum estadoUsuario {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        SANCIONADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        PASAPORTE,
        
        /// <remarks/>
        CARNET_DE_EXTRANJERIA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class bibliotecarioDTO : usuarioDTO {
        
        private bibliotecaDTO bibliotecaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bibliotecaDTO biblioteca {
            get {
                return this.bibliotecaField;
            }
            set {
                this.bibliotecaField = value;
                this.RaisePropertyChanged("biblioteca");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class docenteDTO : usuarioDTO {
        
        private string departamentoAcademicoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string departamentoAcademico {
            get {
                return this.departamentoAcademicoField;
            }
            set {
                this.departamentoAcademicoField = value;
                this.RaisePropertyChanged("departamentoAcademico");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.softinv.pucp.edu.pe/")]
    public partial class estudianteDTO : usuarioDTO {
        
        private string especialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", ConfigurationName="UsuarioWS.UsuarioWS")]
    public interface UsuarioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/obtenerUsuarioPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/UsuarioWS/obtenerUsuarioPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.UsuarioWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/obtenerUsuarioPorId/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdResponse obtenerUsuarioPorId(SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/obtenerUsuarioPorIdRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/UsuarioWS/obtenerUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdResponse> obtenerUsuarioPorIdAsync(SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/insertarUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/UsuarioWS/insertarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.UsuarioWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/insertarUsuario/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.UsuarioWS.insertarUsuarioResponse insertarUsuario(SoftInvWAProg3.UsuarioWS.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/insertarUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/UsuarioWS/insertarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.insertarUsuarioResponse> insertarUsuarioAsync(SoftInvWAProg3.UsuarioWS.insertarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/validarUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/UsuarioWS/validarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftInvWAProg3.UsuarioWS.SQLException), Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/validarUsuario/Fault/SQLException", Name="SQLException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.UsuarioWS.validarUsuarioResponse validarUsuario(SoftInvWAProg3.UsuarioWS.validarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/validarUsuarioRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/UsuarioWS/validarUsuarioResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.validarUsuarioResponse> validarUsuarioAsync(SoftInvWAProg3.UsuarioWS.validarUsuarioRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/buscarUsuariosAvanzadoRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/UsuarioWS/buscarUsuariosAvanzadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoResponse buscarUsuariosAvanzado(SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.softinv.pucp.edu.pe/UsuarioWS/buscarUsuariosAvanzadoRequest", ReplyAction="http://ws.softinv.pucp.edu.pe/UsuarioWS/buscarUsuariosAvanzadoResponse")]
        System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoResponse> buscarUsuariosAvanzadoAsync(SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUsuarioPorId", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUsuarioPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public obtenerUsuarioPorIdRequest() {
        }
        
        public obtenerUsuarioPorIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerUsuarioPorIdResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerUsuarioPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.UsuarioWS.usuarioDTO @return;
        
        public obtenerUsuarioPorIdResponse() {
        }
        
        public obtenerUsuarioPorIdResponse(SoftInvWAProg3.UsuarioWS.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuario", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.UsuarioWS.usuarioDTO usuario;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(SoftInvWAProg3.UsuarioWS.usuarioDTO usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarUsuarioResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarUsuario", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class validarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasena;
        
        public validarUsuarioRequest() {
        }
        
        public validarUsuarioRequest(string correo, string contrasena) {
            this.correo = correo;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarUsuarioResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class validarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.UsuarioWS.usuarioDTO @return;
        
        public validarUsuarioResponse() {
        }
        
        public validarUsuarioResponse(SoftInvWAProg3.UsuarioWS.usuarioDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarUsuariosAvanzado", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarUsuariosAvanzadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoUniversitario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string primerApellido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estado;
        
        public buscarUsuariosAvanzadoRequest() {
        }
        
        public buscarUsuariosAvanzadoRequest(string idUsuario, string tipoUsuario, string codigoUniversitario, string nombres, string primerApellido, string estado) {
            this.idUsuario = idUsuario;
            this.tipoUsuario = tipoUsuario;
            this.codigoUniversitario = codigoUniversitario;
            this.nombres = nombres;
            this.primerApellido = primerApellido;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarUsuariosAvanzadoResponse", WrapperNamespace="http://ws.softinv.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarUsuariosAvanzadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.softinv.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftInvWAProg3.UsuarioWS.usuarioDTO[] @return;
        
        public buscarUsuariosAvanzadoResponse() {
        }
        
        public buscarUsuariosAvanzadoResponse(SoftInvWAProg3.UsuarioWS.usuarioDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioWSChannel : SoftInvWAProg3.UsuarioWS.UsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioWSClient : System.ServiceModel.ClientBase<SoftInvWAProg3.UsuarioWS.UsuarioWS>, SoftInvWAProg3.UsuarioWS.UsuarioWS {
        
        public UsuarioWSClient() {
        }
        
        public UsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdResponse SoftInvWAProg3.UsuarioWS.UsuarioWS.obtenerUsuarioPorId(SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdRequest request) {
            return base.Channel.obtenerUsuarioPorId(request);
        }
        
        public SoftInvWAProg3.UsuarioWS.usuarioDTO obtenerUsuarioPorId(int id) {
            SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdRequest inValue = new SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdRequest();
            inValue.id = id;
            SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdResponse retVal = ((SoftInvWAProg3.UsuarioWS.UsuarioWS)(this)).obtenerUsuarioPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdResponse> SoftInvWAProg3.UsuarioWS.UsuarioWS.obtenerUsuarioPorIdAsync(SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdRequest request) {
            return base.Channel.obtenerUsuarioPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdResponse> obtenerUsuarioPorIdAsync(int id) {
            SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdRequest inValue = new SoftInvWAProg3.UsuarioWS.obtenerUsuarioPorIdRequest();
            inValue.id = id;
            return ((SoftInvWAProg3.UsuarioWS.UsuarioWS)(this)).obtenerUsuarioPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.UsuarioWS.insertarUsuarioResponse SoftInvWAProg3.UsuarioWS.UsuarioWS.insertarUsuario(SoftInvWAProg3.UsuarioWS.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public int insertarUsuario(SoftInvWAProg3.UsuarioWS.usuarioDTO usuario) {
            SoftInvWAProg3.UsuarioWS.insertarUsuarioRequest inValue = new SoftInvWAProg3.UsuarioWS.insertarUsuarioRequest();
            inValue.usuario = usuario;
            SoftInvWAProg3.UsuarioWS.insertarUsuarioResponse retVal = ((SoftInvWAProg3.UsuarioWS.UsuarioWS)(this)).insertarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.insertarUsuarioResponse> SoftInvWAProg3.UsuarioWS.UsuarioWS.insertarUsuarioAsync(SoftInvWAProg3.UsuarioWS.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.insertarUsuarioResponse> insertarUsuarioAsync(SoftInvWAProg3.UsuarioWS.usuarioDTO usuario) {
            SoftInvWAProg3.UsuarioWS.insertarUsuarioRequest inValue = new SoftInvWAProg3.UsuarioWS.insertarUsuarioRequest();
            inValue.usuario = usuario;
            return ((SoftInvWAProg3.UsuarioWS.UsuarioWS)(this)).insertarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.UsuarioWS.validarUsuarioResponse SoftInvWAProg3.UsuarioWS.UsuarioWS.validarUsuario(SoftInvWAProg3.UsuarioWS.validarUsuarioRequest request) {
            return base.Channel.validarUsuario(request);
        }
        
        public SoftInvWAProg3.UsuarioWS.usuarioDTO validarUsuario(string correo, string contrasena) {
            SoftInvWAProg3.UsuarioWS.validarUsuarioRequest inValue = new SoftInvWAProg3.UsuarioWS.validarUsuarioRequest();
            inValue.correo = correo;
            inValue.contrasena = contrasena;
            SoftInvWAProg3.UsuarioWS.validarUsuarioResponse retVal = ((SoftInvWAProg3.UsuarioWS.UsuarioWS)(this)).validarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.validarUsuarioResponse> SoftInvWAProg3.UsuarioWS.UsuarioWS.validarUsuarioAsync(SoftInvWAProg3.UsuarioWS.validarUsuarioRequest request) {
            return base.Channel.validarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.validarUsuarioResponse> validarUsuarioAsync(string correo, string contrasena) {
            SoftInvWAProg3.UsuarioWS.validarUsuarioRequest inValue = new SoftInvWAProg3.UsuarioWS.validarUsuarioRequest();
            inValue.correo = correo;
            inValue.contrasena = contrasena;
            return ((SoftInvWAProg3.UsuarioWS.UsuarioWS)(this)).validarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoResponse SoftInvWAProg3.UsuarioWS.UsuarioWS.buscarUsuariosAvanzado(SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoRequest request) {
            return base.Channel.buscarUsuariosAvanzado(request);
        }
        
        public SoftInvWAProg3.UsuarioWS.usuarioDTO[] buscarUsuariosAvanzado(string idUsuario, string tipoUsuario, string codigoUniversitario, string nombres, string primerApellido, string estado) {
            SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoRequest inValue = new SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoRequest();
            inValue.idUsuario = idUsuario;
            inValue.tipoUsuario = tipoUsuario;
            inValue.codigoUniversitario = codigoUniversitario;
            inValue.nombres = nombres;
            inValue.primerApellido = primerApellido;
            inValue.estado = estado;
            SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoResponse retVal = ((SoftInvWAProg3.UsuarioWS.UsuarioWS)(this)).buscarUsuariosAvanzado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoResponse> SoftInvWAProg3.UsuarioWS.UsuarioWS.buscarUsuariosAvanzadoAsync(SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoRequest request) {
            return base.Channel.buscarUsuariosAvanzadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoResponse> buscarUsuariosAvanzadoAsync(string idUsuario, string tipoUsuario, string codigoUniversitario, string nombres, string primerApellido, string estado) {
            SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoRequest inValue = new SoftInvWAProg3.UsuarioWS.buscarUsuariosAvanzadoRequest();
            inValue.idUsuario = idUsuario;
            inValue.tipoUsuario = tipoUsuario;
            inValue.codigoUniversitario = codigoUniversitario;
            inValue.nombres = nombres;
            inValue.primerApellido = primerApellido;
            inValue.estado = estado;
            return ((SoftInvWAProg3.UsuarioWS.UsuarioWS)(this)).buscarUsuariosAvanzadoAsync(inValue);
        }
    }
}
